/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../../../../common";

export type SignatureRequestStruct = {
  message: PromiseOrValue<BytesLike>;
  isSelectableByUser: PromiseOrValue<boolean>;
  extraData: PromiseOrValue<BytesLike>;
};

export type SignatureRequestStructOutput = [string, boolean, string] & {
  message: string;
  isSelectableByUser: boolean;
  extraData: string;
};

export interface SismoConnectInterface extends utils.Interface {
  functions: {
    "ADDRESSES_PROVIDER()": FunctionFragment;
    "SISMO_CONNECT_LIB_VERSION()": FunctionFragment;
    "appId()": FunctionFragment;
    "buildSignature(bool)": FunctionFragment;
    "buildSignature(bytes,bytes)": FunctionFragment;
    "buildSignature(bool,bytes)": FunctionFragment;
    "buildSignature(bytes,bool,bytes)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "ADDRESSES_PROVIDER"
      | "SISMO_CONNECT_LIB_VERSION"
      | "appId"
      | "buildSignature(bool)"
      | "buildSignature(bytes,bytes)"
      | "buildSignature(bool,bytes)"
      | "buildSignature(bytes,bool,bytes)"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "ADDRESSES_PROVIDER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SISMO_CONNECT_LIB_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "appId", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "buildSignature(bool)",
    values: [PromiseOrValue<boolean>]
  ): string;
  encodeFunctionData(
    functionFragment: "buildSignature(bytes,bytes)",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "buildSignature(bool,bytes)",
    values: [PromiseOrValue<boolean>, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "buildSignature(bytes,bool,bytes)",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<boolean>,
      PromiseOrValue<BytesLike>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "ADDRESSES_PROVIDER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SISMO_CONNECT_LIB_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "appId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "buildSignature(bool)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "buildSignature(bytes,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "buildSignature(bool,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "buildSignature(bytes,bool,bytes)",
    data: BytesLike
  ): Result;

  events: {};
}

export interface SismoConnect extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: SismoConnectInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    ADDRESSES_PROVIDER(overrides?: CallOverrides): Promise<[string]>;

    SISMO_CONNECT_LIB_VERSION(overrides?: CallOverrides): Promise<[BigNumber]>;

    appId(overrides?: CallOverrides): Promise<[string]>;

    "buildSignature(bool)"(
      isSelectableByUser: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<[SignatureRequestStructOutput]>;

    "buildSignature(bytes,bytes)"(
      message: PromiseOrValue<BytesLike>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[SignatureRequestStructOutput]>;

    "buildSignature(bool,bytes)"(
      isSelectableByUser: PromiseOrValue<boolean>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[SignatureRequestStructOutput]>;

    "buildSignature(bytes,bool,bytes)"(
      message: PromiseOrValue<BytesLike>,
      isSelectableByUser: PromiseOrValue<boolean>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[SignatureRequestStructOutput]>;
  };

  ADDRESSES_PROVIDER(overrides?: CallOverrides): Promise<string>;

  SISMO_CONNECT_LIB_VERSION(overrides?: CallOverrides): Promise<BigNumber>;

  appId(overrides?: CallOverrides): Promise<string>;

  "buildSignature(bool)"(
    isSelectableByUser: PromiseOrValue<boolean>,
    overrides?: CallOverrides
  ): Promise<SignatureRequestStructOutput>;

  "buildSignature(bytes,bytes)"(
    message: PromiseOrValue<BytesLike>,
    extraData: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<SignatureRequestStructOutput>;

  "buildSignature(bool,bytes)"(
    isSelectableByUser: PromiseOrValue<boolean>,
    extraData: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<SignatureRequestStructOutput>;

  "buildSignature(bytes,bool,bytes)"(
    message: PromiseOrValue<BytesLike>,
    isSelectableByUser: PromiseOrValue<boolean>,
    extraData: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<SignatureRequestStructOutput>;

  callStatic: {
    ADDRESSES_PROVIDER(overrides?: CallOverrides): Promise<string>;

    SISMO_CONNECT_LIB_VERSION(overrides?: CallOverrides): Promise<BigNumber>;

    appId(overrides?: CallOverrides): Promise<string>;

    "buildSignature(bool)"(
      isSelectableByUser: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<SignatureRequestStructOutput>;

    "buildSignature(bytes,bytes)"(
      message: PromiseOrValue<BytesLike>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<SignatureRequestStructOutput>;

    "buildSignature(bool,bytes)"(
      isSelectableByUser: PromiseOrValue<boolean>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<SignatureRequestStructOutput>;

    "buildSignature(bytes,bool,bytes)"(
      message: PromiseOrValue<BytesLike>,
      isSelectableByUser: PromiseOrValue<boolean>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<SignatureRequestStructOutput>;
  };

  filters: {};

  estimateGas: {
    ADDRESSES_PROVIDER(overrides?: CallOverrides): Promise<BigNumber>;

    SISMO_CONNECT_LIB_VERSION(overrides?: CallOverrides): Promise<BigNumber>;

    appId(overrides?: CallOverrides): Promise<BigNumber>;

    "buildSignature(bool)"(
      isSelectableByUser: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "buildSignature(bytes,bytes)"(
      message: PromiseOrValue<BytesLike>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "buildSignature(bool,bytes)"(
      isSelectableByUser: PromiseOrValue<boolean>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "buildSignature(bytes,bool,bytes)"(
      message: PromiseOrValue<BytesLike>,
      isSelectableByUser: PromiseOrValue<boolean>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    ADDRESSES_PROVIDER(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    SISMO_CONNECT_LIB_VERSION(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    appId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "buildSignature(bool)"(
      isSelectableByUser: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "buildSignature(bytes,bytes)"(
      message: PromiseOrValue<BytesLike>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "buildSignature(bool,bytes)"(
      isSelectableByUser: PromiseOrValue<boolean>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "buildSignature(bytes,bool,bytes)"(
      message: PromiseOrValue<BytesLike>,
      isSelectableByUser: PromiseOrValue<boolean>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
