/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as sismoConnect from "./sismo-connect";
export type { sismoConnect };
import type * as utils from "./utils";
export type { utils };
