/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../../../common";

export type SignatureRequestStruct = {
  message: PromiseOrValue<BytesLike>;
  isSelectableByUser: PromiseOrValue<boolean>;
  extraData: PromiseOrValue<BytesLike>;
};

export type SignatureRequestStructOutput = [string, boolean, string] & {
  message: string;
  isSelectableByUser: boolean;
  extraData: string;
};

export interface SignatureBuilderInterface extends utils.Interface {
  functions: {
    "DEFAULT_SIGNATURE_REQUEST_EXTRA_DATA()": FunctionFragment;
    "DEFAULT_SIGNATURE_REQUEST_IS_SELECTABLE_BY_USER()": FunctionFragment;
    "DEFAULT_SIGNATURE_REQUEST_MESSAGE()": FunctionFragment;
    "build(bytes,bool,bytes)": FunctionFragment;
    "build(bool)": FunctionFragment;
    "build(bytes,bytes)": FunctionFragment;
    "build(bytes,bool)": FunctionFragment;
    "build(bytes)": FunctionFragment;
    "build(bool,bytes)": FunctionFragment;
    "buildEmpty()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "DEFAULT_SIGNATURE_REQUEST_EXTRA_DATA"
      | "DEFAULT_SIGNATURE_REQUEST_IS_SELECTABLE_BY_USER"
      | "DEFAULT_SIGNATURE_REQUEST_MESSAGE"
      | "build(bytes,bool,bytes)"
      | "build(bool)"
      | "build(bytes,bytes)"
      | "build(bytes,bool)"
      | "build(bytes)"
      | "build(bool,bytes)"
      | "buildEmpty"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_SIGNATURE_REQUEST_EXTRA_DATA",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_SIGNATURE_REQUEST_IS_SELECTABLE_BY_USER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_SIGNATURE_REQUEST_MESSAGE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "build(bytes,bool,bytes)",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<boolean>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "build(bool)",
    values: [PromiseOrValue<boolean>]
  ): string;
  encodeFunctionData(
    functionFragment: "build(bytes,bytes)",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "build(bytes,bool)",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<boolean>]
  ): string;
  encodeFunctionData(
    functionFragment: "build(bytes)",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "build(bool,bytes)",
    values: [PromiseOrValue<boolean>, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "buildEmpty",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_SIGNATURE_REQUEST_EXTRA_DATA",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_SIGNATURE_REQUEST_IS_SELECTABLE_BY_USER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_SIGNATURE_REQUEST_MESSAGE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "build(bytes,bool,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "build(bool)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "build(bytes,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "build(bytes,bool)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "build(bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "build(bool,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "buildEmpty", data: BytesLike): Result;

  events: {};
}

export interface SignatureBuilder extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: SignatureBuilderInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    DEFAULT_SIGNATURE_REQUEST_EXTRA_DATA(
      overrides?: CallOverrides
    ): Promise<[string]>;

    DEFAULT_SIGNATURE_REQUEST_IS_SELECTABLE_BY_USER(
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    DEFAULT_SIGNATURE_REQUEST_MESSAGE(
      overrides?: CallOverrides
    ): Promise<[string]>;

    "build(bytes,bool,bytes)"(
      message: PromiseOrValue<BytesLike>,
      isSelectableByUser: PromiseOrValue<boolean>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[SignatureRequestStructOutput]>;

    "build(bool)"(
      isSelectableByUser: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<[SignatureRequestStructOutput]>;

    "build(bytes,bytes)"(
      message: PromiseOrValue<BytesLike>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[SignatureRequestStructOutput]>;

    "build(bytes,bool)"(
      message: PromiseOrValue<BytesLike>,
      isSelectableByUser: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<[SignatureRequestStructOutput]>;

    "build(bytes)"(
      message: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[SignatureRequestStructOutput]>;

    "build(bool,bytes)"(
      isSelectableByUser: PromiseOrValue<boolean>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[SignatureRequestStructOutput]>;

    buildEmpty(
      overrides?: CallOverrides
    ): Promise<[SignatureRequestStructOutput]>;
  };

  DEFAULT_SIGNATURE_REQUEST_EXTRA_DATA(
    overrides?: CallOverrides
  ): Promise<string>;

  DEFAULT_SIGNATURE_REQUEST_IS_SELECTABLE_BY_USER(
    overrides?: CallOverrides
  ): Promise<boolean>;

  DEFAULT_SIGNATURE_REQUEST_MESSAGE(overrides?: CallOverrides): Promise<string>;

  "build(bytes,bool,bytes)"(
    message: PromiseOrValue<BytesLike>,
    isSelectableByUser: PromiseOrValue<boolean>,
    extraData: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<SignatureRequestStructOutput>;

  "build(bool)"(
    isSelectableByUser: PromiseOrValue<boolean>,
    overrides?: CallOverrides
  ): Promise<SignatureRequestStructOutput>;

  "build(bytes,bytes)"(
    message: PromiseOrValue<BytesLike>,
    extraData: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<SignatureRequestStructOutput>;

  "build(bytes,bool)"(
    message: PromiseOrValue<BytesLike>,
    isSelectableByUser: PromiseOrValue<boolean>,
    overrides?: CallOverrides
  ): Promise<SignatureRequestStructOutput>;

  "build(bytes)"(
    message: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<SignatureRequestStructOutput>;

  "build(bool,bytes)"(
    isSelectableByUser: PromiseOrValue<boolean>,
    extraData: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<SignatureRequestStructOutput>;

  buildEmpty(overrides?: CallOverrides): Promise<SignatureRequestStructOutput>;

  callStatic: {
    DEFAULT_SIGNATURE_REQUEST_EXTRA_DATA(
      overrides?: CallOverrides
    ): Promise<string>;

    DEFAULT_SIGNATURE_REQUEST_IS_SELECTABLE_BY_USER(
      overrides?: CallOverrides
    ): Promise<boolean>;

    DEFAULT_SIGNATURE_REQUEST_MESSAGE(
      overrides?: CallOverrides
    ): Promise<string>;

    "build(bytes,bool,bytes)"(
      message: PromiseOrValue<BytesLike>,
      isSelectableByUser: PromiseOrValue<boolean>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<SignatureRequestStructOutput>;

    "build(bool)"(
      isSelectableByUser: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<SignatureRequestStructOutput>;

    "build(bytes,bytes)"(
      message: PromiseOrValue<BytesLike>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<SignatureRequestStructOutput>;

    "build(bytes,bool)"(
      message: PromiseOrValue<BytesLike>,
      isSelectableByUser: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<SignatureRequestStructOutput>;

    "build(bytes)"(
      message: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<SignatureRequestStructOutput>;

    "build(bool,bytes)"(
      isSelectableByUser: PromiseOrValue<boolean>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<SignatureRequestStructOutput>;

    buildEmpty(
      overrides?: CallOverrides
    ): Promise<SignatureRequestStructOutput>;
  };

  filters: {};

  estimateGas: {
    DEFAULT_SIGNATURE_REQUEST_EXTRA_DATA(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    DEFAULT_SIGNATURE_REQUEST_IS_SELECTABLE_BY_USER(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    DEFAULT_SIGNATURE_REQUEST_MESSAGE(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "build(bytes,bool,bytes)"(
      message: PromiseOrValue<BytesLike>,
      isSelectableByUser: PromiseOrValue<boolean>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "build(bool)"(
      isSelectableByUser: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "build(bytes,bytes)"(
      message: PromiseOrValue<BytesLike>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "build(bytes,bool)"(
      message: PromiseOrValue<BytesLike>,
      isSelectableByUser: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "build(bytes)"(
      message: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "build(bool,bytes)"(
      isSelectableByUser: PromiseOrValue<boolean>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    buildEmpty(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    DEFAULT_SIGNATURE_REQUEST_EXTRA_DATA(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    DEFAULT_SIGNATURE_REQUEST_IS_SELECTABLE_BY_USER(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    DEFAULT_SIGNATURE_REQUEST_MESSAGE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "build(bytes,bool,bytes)"(
      message: PromiseOrValue<BytesLike>,
      isSelectableByUser: PromiseOrValue<boolean>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "build(bool)"(
      isSelectableByUser: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "build(bytes,bytes)"(
      message: PromiseOrValue<BytesLike>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "build(bytes,bool)"(
      message: PromiseOrValue<BytesLike>,
      isSelectableByUser: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "build(bytes)"(
      message: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "build(bool,bytes)"(
      isSelectableByUser: PromiseOrValue<boolean>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    buildEmpty(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
