/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../../../common";

export type AuthRequestStruct = {
  authType: PromiseOrValue<BigNumberish>;
  userId: PromiseOrValue<BigNumberish>;
  isAnon: PromiseOrValue<boolean>;
  isOptional: PromiseOrValue<boolean>;
  isSelectableByUser: PromiseOrValue<boolean>;
  extraData: PromiseOrValue<BytesLike>;
};

export type AuthRequestStructOutput = [
  number,
  BigNumber,
  boolean,
  boolean,
  boolean,
  string
] & {
  authType: number;
  userId: BigNumber;
  isAnon: boolean;
  isOptional: boolean;
  isSelectableByUser: boolean;
  extraData: string;
};

export interface AuthRequestBuilderInterface extends utils.Interface {
  functions: {
    "DEFAULT_AUTH_REQUEST_EXTRA_DATA()": FunctionFragment;
    "DEFAULT_AUTH_REQUEST_IS_ANON()": FunctionFragment;
    "DEFAULT_AUTH_REQUEST_IS_OPTIONAL()": FunctionFragment;
    "DEFAULT_AUTH_REQUEST_USER_ID()": FunctionFragment;
    "build(uint8,bool,bytes)": FunctionFragment;
    "build(uint8,bool)": FunctionFragment;
    "build(uint8,bool,bool,bool)": FunctionFragment;
    "build(uint8,bool,bool,uint256)": FunctionFragment;
    "build(uint8)": FunctionFragment;
    "build(uint8,uint256,bool)": FunctionFragment;
    "build(uint8,uint256)": FunctionFragment;
    "build(uint8,bytes)": FunctionFragment;
    "build(uint8,bool,uint256)": FunctionFragment;
    "build(uint8,bool,uint256,bool)": FunctionFragment;
    "build(uint8,bool,uint256,bool,bool,bytes)": FunctionFragment;
    "build(uint8,uint256,bytes)": FunctionFragment;
    "build(uint8,bool,uint256,bytes)": FunctionFragment;
    "build(uint8,bool,bool)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "DEFAULT_AUTH_REQUEST_EXTRA_DATA"
      | "DEFAULT_AUTH_REQUEST_IS_ANON"
      | "DEFAULT_AUTH_REQUEST_IS_OPTIONAL"
      | "DEFAULT_AUTH_REQUEST_USER_ID"
      | "build(uint8,bool,bytes)"
      | "build(uint8,bool)"
      | "build(uint8,bool,bool,bool)"
      | "build(uint8,bool,bool,uint256)"
      | "build(uint8)"
      | "build(uint8,uint256,bool)"
      | "build(uint8,uint256)"
      | "build(uint8,bytes)"
      | "build(uint8,bool,uint256)"
      | "build(uint8,bool,uint256,bool)"
      | "build(uint8,bool,uint256,bool,bool,bytes)"
      | "build(uint8,uint256,bytes)"
      | "build(uint8,bool,uint256,bytes)"
      | "build(uint8,bool,bool)"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_AUTH_REQUEST_EXTRA_DATA",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_AUTH_REQUEST_IS_ANON",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_AUTH_REQUEST_IS_OPTIONAL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_AUTH_REQUEST_USER_ID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "build(uint8,bool,bytes)",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<boolean>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "build(uint8,bool)",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<boolean>]
  ): string;
  encodeFunctionData(
    functionFragment: "build(uint8,bool,bool,bool)",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<boolean>,
      PromiseOrValue<boolean>,
      PromiseOrValue<boolean>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "build(uint8,bool,bool,uint256)",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<boolean>,
      PromiseOrValue<boolean>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "build(uint8)",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "build(uint8,uint256,bool)",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<boolean>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "build(uint8,uint256)",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "build(uint8,bytes)",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "build(uint8,bool,uint256)",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<boolean>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "build(uint8,bool,uint256,bool)",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<boolean>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<boolean>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "build(uint8,bool,uint256,bool,bool,bytes)",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<boolean>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<boolean>,
      PromiseOrValue<boolean>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "build(uint8,uint256,bytes)",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "build(uint8,bool,uint256,bytes)",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<boolean>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "build(uint8,bool,bool)",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<boolean>,
      PromiseOrValue<boolean>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_AUTH_REQUEST_EXTRA_DATA",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_AUTH_REQUEST_IS_ANON",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_AUTH_REQUEST_IS_OPTIONAL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_AUTH_REQUEST_USER_ID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "build(uint8,bool,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "build(uint8,bool)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "build(uint8,bool,bool,bool)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "build(uint8,bool,bool,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "build(uint8)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "build(uint8,uint256,bool)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "build(uint8,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "build(uint8,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "build(uint8,bool,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "build(uint8,bool,uint256,bool)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "build(uint8,bool,uint256,bool,bool,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "build(uint8,uint256,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "build(uint8,bool,uint256,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "build(uint8,bool,bool)",
    data: BytesLike
  ): Result;

  events: {};
}

export interface AuthRequestBuilder extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: AuthRequestBuilderInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    DEFAULT_AUTH_REQUEST_EXTRA_DATA(
      overrides?: CallOverrides
    ): Promise<[string]>;

    DEFAULT_AUTH_REQUEST_IS_ANON(overrides?: CallOverrides): Promise<[boolean]>;

    DEFAULT_AUTH_REQUEST_IS_OPTIONAL(
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    DEFAULT_AUTH_REQUEST_USER_ID(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "build(uint8,bool,bytes)"(
      authType: PromiseOrValue<BigNumberish>,
      isAnon: PromiseOrValue<boolean>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[AuthRequestStructOutput]>;

    "build(uint8,bool)"(
      authType: PromiseOrValue<BigNumberish>,
      isAnon: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<[AuthRequestStructOutput]>;

    "build(uint8,bool,bool,bool)"(
      authType: PromiseOrValue<BigNumberish>,
      isAnon: PromiseOrValue<boolean>,
      isOptional: PromiseOrValue<boolean>,
      isSelectableByUser: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<[AuthRequestStructOutput]>;

    "build(uint8,bool,bool,uint256)"(
      authType: PromiseOrValue<BigNumberish>,
      isOptional: PromiseOrValue<boolean>,
      isSelectableByUser: PromiseOrValue<boolean>,
      userId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[AuthRequestStructOutput]>;

    "build(uint8)"(
      authType: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[AuthRequestStructOutput]>;

    "build(uint8,uint256,bool)"(
      authType: PromiseOrValue<BigNumberish>,
      userId: PromiseOrValue<BigNumberish>,
      isOptional: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<[AuthRequestStructOutput]>;

    "build(uint8,uint256)"(
      authType: PromiseOrValue<BigNumberish>,
      userId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[AuthRequestStructOutput]>;

    "build(uint8,bytes)"(
      authType: PromiseOrValue<BigNumberish>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[AuthRequestStructOutput]>;

    "build(uint8,bool,uint256)"(
      authType: PromiseOrValue<BigNumberish>,
      isAnon: PromiseOrValue<boolean>,
      userId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[AuthRequestStructOutput]>;

    "build(uint8,bool,uint256,bool)"(
      authType: PromiseOrValue<BigNumberish>,
      isAnon: PromiseOrValue<boolean>,
      userId: PromiseOrValue<BigNumberish>,
      isOptional: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<[AuthRequestStructOutput]>;

    "build(uint8,bool,uint256,bool,bool,bytes)"(
      authType: PromiseOrValue<BigNumberish>,
      isAnon: PromiseOrValue<boolean>,
      userId: PromiseOrValue<BigNumberish>,
      isOptional: PromiseOrValue<boolean>,
      isSelectableByUser: PromiseOrValue<boolean>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[AuthRequestStructOutput]>;

    "build(uint8,uint256,bytes)"(
      authType: PromiseOrValue<BigNumberish>,
      userId: PromiseOrValue<BigNumberish>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[AuthRequestStructOutput]>;

    "build(uint8,bool,uint256,bytes)"(
      authType: PromiseOrValue<BigNumberish>,
      isAnon: PromiseOrValue<boolean>,
      userId: PromiseOrValue<BigNumberish>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[AuthRequestStructOutput]>;

    "build(uint8,bool,bool)"(
      authType: PromiseOrValue<BigNumberish>,
      isOptional: PromiseOrValue<boolean>,
      isSelectableByUser: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<[AuthRequestStructOutput]>;
  };

  DEFAULT_AUTH_REQUEST_EXTRA_DATA(overrides?: CallOverrides): Promise<string>;

  DEFAULT_AUTH_REQUEST_IS_ANON(overrides?: CallOverrides): Promise<boolean>;

  DEFAULT_AUTH_REQUEST_IS_OPTIONAL(overrides?: CallOverrides): Promise<boolean>;

  DEFAULT_AUTH_REQUEST_USER_ID(overrides?: CallOverrides): Promise<BigNumber>;

  "build(uint8,bool,bytes)"(
    authType: PromiseOrValue<BigNumberish>,
    isAnon: PromiseOrValue<boolean>,
    extraData: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<AuthRequestStructOutput>;

  "build(uint8,bool)"(
    authType: PromiseOrValue<BigNumberish>,
    isAnon: PromiseOrValue<boolean>,
    overrides?: CallOverrides
  ): Promise<AuthRequestStructOutput>;

  "build(uint8,bool,bool,bool)"(
    authType: PromiseOrValue<BigNumberish>,
    isAnon: PromiseOrValue<boolean>,
    isOptional: PromiseOrValue<boolean>,
    isSelectableByUser: PromiseOrValue<boolean>,
    overrides?: CallOverrides
  ): Promise<AuthRequestStructOutput>;

  "build(uint8,bool,bool,uint256)"(
    authType: PromiseOrValue<BigNumberish>,
    isOptional: PromiseOrValue<boolean>,
    isSelectableByUser: PromiseOrValue<boolean>,
    userId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<AuthRequestStructOutput>;

  "build(uint8)"(
    authType: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<AuthRequestStructOutput>;

  "build(uint8,uint256,bool)"(
    authType: PromiseOrValue<BigNumberish>,
    userId: PromiseOrValue<BigNumberish>,
    isOptional: PromiseOrValue<boolean>,
    overrides?: CallOverrides
  ): Promise<AuthRequestStructOutput>;

  "build(uint8,uint256)"(
    authType: PromiseOrValue<BigNumberish>,
    userId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<AuthRequestStructOutput>;

  "build(uint8,bytes)"(
    authType: PromiseOrValue<BigNumberish>,
    extraData: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<AuthRequestStructOutput>;

  "build(uint8,bool,uint256)"(
    authType: PromiseOrValue<BigNumberish>,
    isAnon: PromiseOrValue<boolean>,
    userId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<AuthRequestStructOutput>;

  "build(uint8,bool,uint256,bool)"(
    authType: PromiseOrValue<BigNumberish>,
    isAnon: PromiseOrValue<boolean>,
    userId: PromiseOrValue<BigNumberish>,
    isOptional: PromiseOrValue<boolean>,
    overrides?: CallOverrides
  ): Promise<AuthRequestStructOutput>;

  "build(uint8,bool,uint256,bool,bool,bytes)"(
    authType: PromiseOrValue<BigNumberish>,
    isAnon: PromiseOrValue<boolean>,
    userId: PromiseOrValue<BigNumberish>,
    isOptional: PromiseOrValue<boolean>,
    isSelectableByUser: PromiseOrValue<boolean>,
    extraData: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<AuthRequestStructOutput>;

  "build(uint8,uint256,bytes)"(
    authType: PromiseOrValue<BigNumberish>,
    userId: PromiseOrValue<BigNumberish>,
    extraData: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<AuthRequestStructOutput>;

  "build(uint8,bool,uint256,bytes)"(
    authType: PromiseOrValue<BigNumberish>,
    isAnon: PromiseOrValue<boolean>,
    userId: PromiseOrValue<BigNumberish>,
    extraData: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<AuthRequestStructOutput>;

  "build(uint8,bool,bool)"(
    authType: PromiseOrValue<BigNumberish>,
    isOptional: PromiseOrValue<boolean>,
    isSelectableByUser: PromiseOrValue<boolean>,
    overrides?: CallOverrides
  ): Promise<AuthRequestStructOutput>;

  callStatic: {
    DEFAULT_AUTH_REQUEST_EXTRA_DATA(overrides?: CallOverrides): Promise<string>;

    DEFAULT_AUTH_REQUEST_IS_ANON(overrides?: CallOverrides): Promise<boolean>;

    DEFAULT_AUTH_REQUEST_IS_OPTIONAL(
      overrides?: CallOverrides
    ): Promise<boolean>;

    DEFAULT_AUTH_REQUEST_USER_ID(overrides?: CallOverrides): Promise<BigNumber>;

    "build(uint8,bool,bytes)"(
      authType: PromiseOrValue<BigNumberish>,
      isAnon: PromiseOrValue<boolean>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<AuthRequestStructOutput>;

    "build(uint8,bool)"(
      authType: PromiseOrValue<BigNumberish>,
      isAnon: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<AuthRequestStructOutput>;

    "build(uint8,bool,bool,bool)"(
      authType: PromiseOrValue<BigNumberish>,
      isAnon: PromiseOrValue<boolean>,
      isOptional: PromiseOrValue<boolean>,
      isSelectableByUser: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<AuthRequestStructOutput>;

    "build(uint8,bool,bool,uint256)"(
      authType: PromiseOrValue<BigNumberish>,
      isOptional: PromiseOrValue<boolean>,
      isSelectableByUser: PromiseOrValue<boolean>,
      userId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<AuthRequestStructOutput>;

    "build(uint8)"(
      authType: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<AuthRequestStructOutput>;

    "build(uint8,uint256,bool)"(
      authType: PromiseOrValue<BigNumberish>,
      userId: PromiseOrValue<BigNumberish>,
      isOptional: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<AuthRequestStructOutput>;

    "build(uint8,uint256)"(
      authType: PromiseOrValue<BigNumberish>,
      userId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<AuthRequestStructOutput>;

    "build(uint8,bytes)"(
      authType: PromiseOrValue<BigNumberish>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<AuthRequestStructOutput>;

    "build(uint8,bool,uint256)"(
      authType: PromiseOrValue<BigNumberish>,
      isAnon: PromiseOrValue<boolean>,
      userId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<AuthRequestStructOutput>;

    "build(uint8,bool,uint256,bool)"(
      authType: PromiseOrValue<BigNumberish>,
      isAnon: PromiseOrValue<boolean>,
      userId: PromiseOrValue<BigNumberish>,
      isOptional: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<AuthRequestStructOutput>;

    "build(uint8,bool,uint256,bool,bool,bytes)"(
      authType: PromiseOrValue<BigNumberish>,
      isAnon: PromiseOrValue<boolean>,
      userId: PromiseOrValue<BigNumberish>,
      isOptional: PromiseOrValue<boolean>,
      isSelectableByUser: PromiseOrValue<boolean>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<AuthRequestStructOutput>;

    "build(uint8,uint256,bytes)"(
      authType: PromiseOrValue<BigNumberish>,
      userId: PromiseOrValue<BigNumberish>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<AuthRequestStructOutput>;

    "build(uint8,bool,uint256,bytes)"(
      authType: PromiseOrValue<BigNumberish>,
      isAnon: PromiseOrValue<boolean>,
      userId: PromiseOrValue<BigNumberish>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<AuthRequestStructOutput>;

    "build(uint8,bool,bool)"(
      authType: PromiseOrValue<BigNumberish>,
      isOptional: PromiseOrValue<boolean>,
      isSelectableByUser: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<AuthRequestStructOutput>;
  };

  filters: {};

  estimateGas: {
    DEFAULT_AUTH_REQUEST_EXTRA_DATA(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    DEFAULT_AUTH_REQUEST_IS_ANON(overrides?: CallOverrides): Promise<BigNumber>;

    DEFAULT_AUTH_REQUEST_IS_OPTIONAL(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    DEFAULT_AUTH_REQUEST_USER_ID(overrides?: CallOverrides): Promise<BigNumber>;

    "build(uint8,bool,bytes)"(
      authType: PromiseOrValue<BigNumberish>,
      isAnon: PromiseOrValue<boolean>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "build(uint8,bool)"(
      authType: PromiseOrValue<BigNumberish>,
      isAnon: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "build(uint8,bool,bool,bool)"(
      authType: PromiseOrValue<BigNumberish>,
      isAnon: PromiseOrValue<boolean>,
      isOptional: PromiseOrValue<boolean>,
      isSelectableByUser: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "build(uint8,bool,bool,uint256)"(
      authType: PromiseOrValue<BigNumberish>,
      isOptional: PromiseOrValue<boolean>,
      isSelectableByUser: PromiseOrValue<boolean>,
      userId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "build(uint8)"(
      authType: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "build(uint8,uint256,bool)"(
      authType: PromiseOrValue<BigNumberish>,
      userId: PromiseOrValue<BigNumberish>,
      isOptional: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "build(uint8,uint256)"(
      authType: PromiseOrValue<BigNumberish>,
      userId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "build(uint8,bytes)"(
      authType: PromiseOrValue<BigNumberish>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "build(uint8,bool,uint256)"(
      authType: PromiseOrValue<BigNumberish>,
      isAnon: PromiseOrValue<boolean>,
      userId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "build(uint8,bool,uint256,bool)"(
      authType: PromiseOrValue<BigNumberish>,
      isAnon: PromiseOrValue<boolean>,
      userId: PromiseOrValue<BigNumberish>,
      isOptional: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "build(uint8,bool,uint256,bool,bool,bytes)"(
      authType: PromiseOrValue<BigNumberish>,
      isAnon: PromiseOrValue<boolean>,
      userId: PromiseOrValue<BigNumberish>,
      isOptional: PromiseOrValue<boolean>,
      isSelectableByUser: PromiseOrValue<boolean>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "build(uint8,uint256,bytes)"(
      authType: PromiseOrValue<BigNumberish>,
      userId: PromiseOrValue<BigNumberish>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "build(uint8,bool,uint256,bytes)"(
      authType: PromiseOrValue<BigNumberish>,
      isAnon: PromiseOrValue<boolean>,
      userId: PromiseOrValue<BigNumberish>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "build(uint8,bool,bool)"(
      authType: PromiseOrValue<BigNumberish>,
      isOptional: PromiseOrValue<boolean>,
      isSelectableByUser: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    DEFAULT_AUTH_REQUEST_EXTRA_DATA(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    DEFAULT_AUTH_REQUEST_IS_ANON(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    DEFAULT_AUTH_REQUEST_IS_OPTIONAL(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    DEFAULT_AUTH_REQUEST_USER_ID(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "build(uint8,bool,bytes)"(
      authType: PromiseOrValue<BigNumberish>,
      isAnon: PromiseOrValue<boolean>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "build(uint8,bool)"(
      authType: PromiseOrValue<BigNumberish>,
      isAnon: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "build(uint8,bool,bool,bool)"(
      authType: PromiseOrValue<BigNumberish>,
      isAnon: PromiseOrValue<boolean>,
      isOptional: PromiseOrValue<boolean>,
      isSelectableByUser: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "build(uint8,bool,bool,uint256)"(
      authType: PromiseOrValue<BigNumberish>,
      isOptional: PromiseOrValue<boolean>,
      isSelectableByUser: PromiseOrValue<boolean>,
      userId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "build(uint8)"(
      authType: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "build(uint8,uint256,bool)"(
      authType: PromiseOrValue<BigNumberish>,
      userId: PromiseOrValue<BigNumberish>,
      isOptional: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "build(uint8,uint256)"(
      authType: PromiseOrValue<BigNumberish>,
      userId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "build(uint8,bytes)"(
      authType: PromiseOrValue<BigNumberish>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "build(uint8,bool,uint256)"(
      authType: PromiseOrValue<BigNumberish>,
      isAnon: PromiseOrValue<boolean>,
      userId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "build(uint8,bool,uint256,bool)"(
      authType: PromiseOrValue<BigNumberish>,
      isAnon: PromiseOrValue<boolean>,
      userId: PromiseOrValue<BigNumberish>,
      isOptional: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "build(uint8,bool,uint256,bool,bool,bytes)"(
      authType: PromiseOrValue<BigNumberish>,
      isAnon: PromiseOrValue<boolean>,
      userId: PromiseOrValue<BigNumberish>,
      isOptional: PromiseOrValue<boolean>,
      isSelectableByUser: PromiseOrValue<boolean>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "build(uint8,uint256,bytes)"(
      authType: PromiseOrValue<BigNumberish>,
      userId: PromiseOrValue<BigNumberish>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "build(uint8,bool,uint256,bytes)"(
      authType: PromiseOrValue<BigNumberish>,
      isAnon: PromiseOrValue<boolean>,
      userId: PromiseOrValue<BigNumberish>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "build(uint8,bool,bool)"(
      authType: PromiseOrValue<BigNumberish>,
      isOptional: PromiseOrValue<boolean>,
      isSelectableByUser: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
