/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../../../common";

export type ClaimRequestStruct = {
  claimType: PromiseOrValue<BigNumberish>;
  groupId: PromiseOrValue<BytesLike>;
  groupTimestamp: PromiseOrValue<BytesLike>;
  value: PromiseOrValue<BigNumberish>;
  isOptional: PromiseOrValue<boolean>;
  isSelectableByUser: PromiseOrValue<boolean>;
  extraData: PromiseOrValue<BytesLike>;
};

export type ClaimRequestStructOutput = [
  number,
  string,
  string,
  BigNumber,
  boolean,
  boolean,
  string
] & {
  claimType: number;
  groupId: string;
  groupTimestamp: string;
  value: BigNumber;
  isOptional: boolean;
  isSelectableByUser: boolean;
  extraData: string;
};

export interface ClaimRequestBuilderInterface extends utils.Interface {
  functions: {
    "DEFAULT_CLAIM_REQUEST_EXTRA_DATA()": FunctionFragment;
    "DEFAULT_CLAIM_REQUEST_GROUP_TIMESTAMP()": FunctionFragment;
    "DEFAULT_CLAIM_REQUEST_IS_OPTIONAL()": FunctionFragment;
    "DEFAULT_CLAIM_REQUEST_IS_SELECTABLE_BY_USER()": FunctionFragment;
    "DEFAULT_CLAIM_REQUEST_TYPE()": FunctionFragment;
    "DEFAULT_CLAIM_REQUEST_VALUE()": FunctionFragment;
    "build(bytes16,bytes16,uint8,bytes)": FunctionFragment;
    "build(bytes16,bytes16,uint256,bytes)": FunctionFragment;
    "build(bytes16,bytes16,bool,bool)": FunctionFragment;
    "build(bytes16,uint256,uint8,bool,bool)": FunctionFragment;
    "build(bytes16,uint256,bool,bool)": FunctionFragment;
    "build(bytes16,bytes16,uint8,bool,bool)": FunctionFragment;
    "build(bytes16,uint256,uint8)": FunctionFragment;
    "build(bytes16,bytes16,uint256)": FunctionFragment;
    "build(bytes16,bytes16)": FunctionFragment;
    "build(bytes16,bytes16,uint256,uint8,bool,bool)": FunctionFragment;
    "build(bytes16,bytes16,uint256,uint8,bytes)": FunctionFragment;
    "build(bytes16,uint8)": FunctionFragment;
    "build(bytes16,uint256)": FunctionFragment;
    "build(bytes16,uint8,bytes)": FunctionFragment;
    "build(bytes16,bytes)": FunctionFragment;
    "build(bytes16,uint8,bool,bool)": FunctionFragment;
    "build(bytes16,bytes16,uint8)": FunctionFragment;
    "build(bytes16,bytes16,uint256,uint8)": FunctionFragment;
    "build(bytes16,bytes16,uint256,bool,bool)": FunctionFragment;
    "build(bytes16,uint256,uint8,bytes)": FunctionFragment;
    "build(bytes16)": FunctionFragment;
    "build(bytes16,bytes16,uint256,uint8,bool,bool,bytes)": FunctionFragment;
    "build(bytes16,uint256,bytes)": FunctionFragment;
    "build(bytes16,bool,bool)": FunctionFragment;
    "build(bytes16,bytes16,bytes)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "DEFAULT_CLAIM_REQUEST_EXTRA_DATA"
      | "DEFAULT_CLAIM_REQUEST_GROUP_TIMESTAMP"
      | "DEFAULT_CLAIM_REQUEST_IS_OPTIONAL"
      | "DEFAULT_CLAIM_REQUEST_IS_SELECTABLE_BY_USER"
      | "DEFAULT_CLAIM_REQUEST_TYPE"
      | "DEFAULT_CLAIM_REQUEST_VALUE"
      | "build(bytes16,bytes16,uint8,bytes)"
      | "build(bytes16,bytes16,uint256,bytes)"
      | "build(bytes16,bytes16,bool,bool)"
      | "build(bytes16,uint256,uint8,bool,bool)"
      | "build(bytes16,uint256,bool,bool)"
      | "build(bytes16,bytes16,uint8,bool,bool)"
      | "build(bytes16,uint256,uint8)"
      | "build(bytes16,bytes16,uint256)"
      | "build(bytes16,bytes16)"
      | "build(bytes16,bytes16,uint256,uint8,bool,bool)"
      | "build(bytes16,bytes16,uint256,uint8,bytes)"
      | "build(bytes16,uint8)"
      | "build(bytes16,uint256)"
      | "build(bytes16,uint8,bytes)"
      | "build(bytes16,bytes)"
      | "build(bytes16,uint8,bool,bool)"
      | "build(bytes16,bytes16,uint8)"
      | "build(bytes16,bytes16,uint256,uint8)"
      | "build(bytes16,bytes16,uint256,bool,bool)"
      | "build(bytes16,uint256,uint8,bytes)"
      | "build(bytes16)"
      | "build(bytes16,bytes16,uint256,uint8,bool,bool,bytes)"
      | "build(bytes16,uint256,bytes)"
      | "build(bytes16,bool,bool)"
      | "build(bytes16,bytes16,bytes)"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_CLAIM_REQUEST_EXTRA_DATA",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_CLAIM_REQUEST_GROUP_TIMESTAMP",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_CLAIM_REQUEST_IS_OPTIONAL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_CLAIM_REQUEST_IS_SELECTABLE_BY_USER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_CLAIM_REQUEST_TYPE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_CLAIM_REQUEST_VALUE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "build(bytes16,bytes16,uint8,bytes)",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "build(bytes16,bytes16,uint256,bytes)",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "build(bytes16,bytes16,bool,bool)",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<boolean>,
      PromiseOrValue<boolean>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "build(bytes16,uint256,uint8,bool,bool)",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<boolean>,
      PromiseOrValue<boolean>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "build(bytes16,uint256,bool,bool)",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<boolean>,
      PromiseOrValue<boolean>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "build(bytes16,bytes16,uint8,bool,bool)",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<boolean>,
      PromiseOrValue<boolean>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "build(bytes16,uint256,uint8)",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "build(bytes16,bytes16,uint256)",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "build(bytes16,bytes16)",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "build(bytes16,bytes16,uint256,uint8,bool,bool)",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<boolean>,
      PromiseOrValue<boolean>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "build(bytes16,bytes16,uint256,uint8,bytes)",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "build(bytes16,uint8)",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "build(bytes16,uint256)",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "build(bytes16,uint8,bytes)",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "build(bytes16,bytes)",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "build(bytes16,uint8,bool,bool)",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<boolean>,
      PromiseOrValue<boolean>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "build(bytes16,bytes16,uint8)",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "build(bytes16,bytes16,uint256,uint8)",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "build(bytes16,bytes16,uint256,bool,bool)",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<boolean>,
      PromiseOrValue<boolean>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "build(bytes16,uint256,uint8,bytes)",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "build(bytes16)",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "build(bytes16,bytes16,uint256,uint8,bool,bool,bytes)",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<boolean>,
      PromiseOrValue<boolean>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "build(bytes16,uint256,bytes)",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "build(bytes16,bool,bool)",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<boolean>,
      PromiseOrValue<boolean>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "build(bytes16,bytes16,bytes)",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_CLAIM_REQUEST_EXTRA_DATA",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_CLAIM_REQUEST_GROUP_TIMESTAMP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_CLAIM_REQUEST_IS_OPTIONAL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_CLAIM_REQUEST_IS_SELECTABLE_BY_USER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_CLAIM_REQUEST_TYPE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_CLAIM_REQUEST_VALUE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "build(bytes16,bytes16,uint8,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "build(bytes16,bytes16,uint256,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "build(bytes16,bytes16,bool,bool)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "build(bytes16,uint256,uint8,bool,bool)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "build(bytes16,uint256,bool,bool)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "build(bytes16,bytes16,uint8,bool,bool)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "build(bytes16,uint256,uint8)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "build(bytes16,bytes16,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "build(bytes16,bytes16)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "build(bytes16,bytes16,uint256,uint8,bool,bool)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "build(bytes16,bytes16,uint256,uint8,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "build(bytes16,uint8)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "build(bytes16,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "build(bytes16,uint8,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "build(bytes16,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "build(bytes16,uint8,bool,bool)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "build(bytes16,bytes16,uint8)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "build(bytes16,bytes16,uint256,uint8)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "build(bytes16,bytes16,uint256,bool,bool)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "build(bytes16,uint256,uint8,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "build(bytes16)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "build(bytes16,bytes16,uint256,uint8,bool,bool,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "build(bytes16,uint256,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "build(bytes16,bool,bool)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "build(bytes16,bytes16,bytes)",
    data: BytesLike
  ): Result;

  events: {};
}

export interface ClaimRequestBuilder extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ClaimRequestBuilderInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    DEFAULT_CLAIM_REQUEST_EXTRA_DATA(
      overrides?: CallOverrides
    ): Promise<[string]>;

    DEFAULT_CLAIM_REQUEST_GROUP_TIMESTAMP(
      overrides?: CallOverrides
    ): Promise<[string]>;

    DEFAULT_CLAIM_REQUEST_IS_OPTIONAL(
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    DEFAULT_CLAIM_REQUEST_IS_SELECTABLE_BY_USER(
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    DEFAULT_CLAIM_REQUEST_TYPE(overrides?: CallOverrides): Promise<[number]>;

    DEFAULT_CLAIM_REQUEST_VALUE(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "build(bytes16,bytes16,uint8,bytes)"(
      groupId: PromiseOrValue<BytesLike>,
      groupTimestamp: PromiseOrValue<BytesLike>,
      claimType: PromiseOrValue<BigNumberish>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[ClaimRequestStructOutput]>;

    "build(bytes16,bytes16,uint256,bytes)"(
      groupId: PromiseOrValue<BytesLike>,
      groupTimestamp: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BigNumberish>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[ClaimRequestStructOutput]>;

    "build(bytes16,bytes16,bool,bool)"(
      groupId: PromiseOrValue<BytesLike>,
      groupTimestamp: PromiseOrValue<BytesLike>,
      isOptional: PromiseOrValue<boolean>,
      isSelectableByUser: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<[ClaimRequestStructOutput]>;

    "build(bytes16,uint256,uint8,bool,bool)"(
      groupId: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BigNumberish>,
      claimType: PromiseOrValue<BigNumberish>,
      isOptional: PromiseOrValue<boolean>,
      isSelectableByUser: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<[ClaimRequestStructOutput]>;

    "build(bytes16,uint256,bool,bool)"(
      groupId: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BigNumberish>,
      isOptional: PromiseOrValue<boolean>,
      isSelectableByUser: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<[ClaimRequestStructOutput]>;

    "build(bytes16,bytes16,uint8,bool,bool)"(
      groupId: PromiseOrValue<BytesLike>,
      groupTimestamp: PromiseOrValue<BytesLike>,
      claimType: PromiseOrValue<BigNumberish>,
      isOptional: PromiseOrValue<boolean>,
      isSelectableByUser: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<[ClaimRequestStructOutput]>;

    "build(bytes16,uint256,uint8)"(
      groupId: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BigNumberish>,
      claimType: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[ClaimRequestStructOutput]>;

    "build(bytes16,bytes16,uint256)"(
      groupId: PromiseOrValue<BytesLike>,
      groupTimestamp: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[ClaimRequestStructOutput]>;

    "build(bytes16,bytes16)"(
      groupId: PromiseOrValue<BytesLike>,
      groupTimestamp: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[ClaimRequestStructOutput]>;

    "build(bytes16,bytes16,uint256,uint8,bool,bool)"(
      groupId: PromiseOrValue<BytesLike>,
      groupTimestamp: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BigNumberish>,
      claimType: PromiseOrValue<BigNumberish>,
      isOptional: PromiseOrValue<boolean>,
      isSelectableByUser: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<[ClaimRequestStructOutput]>;

    "build(bytes16,bytes16,uint256,uint8,bytes)"(
      groupId: PromiseOrValue<BytesLike>,
      groupTimestamp: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BigNumberish>,
      claimType: PromiseOrValue<BigNumberish>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[ClaimRequestStructOutput]>;

    "build(bytes16,uint8)"(
      groupId: PromiseOrValue<BytesLike>,
      claimType: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[ClaimRequestStructOutput]>;

    "build(bytes16,uint256)"(
      groupId: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[ClaimRequestStructOutput]>;

    "build(bytes16,uint8,bytes)"(
      groupId: PromiseOrValue<BytesLike>,
      claimType: PromiseOrValue<BigNumberish>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[ClaimRequestStructOutput]>;

    "build(bytes16,bytes)"(
      groupId: PromiseOrValue<BytesLike>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[ClaimRequestStructOutput]>;

    "build(bytes16,uint8,bool,bool)"(
      groupId: PromiseOrValue<BytesLike>,
      claimType: PromiseOrValue<BigNumberish>,
      isOptional: PromiseOrValue<boolean>,
      isSelectableByUser: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<[ClaimRequestStructOutput]>;

    "build(bytes16,bytes16,uint8)"(
      groupId: PromiseOrValue<BytesLike>,
      groupTimestamp: PromiseOrValue<BytesLike>,
      claimType: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[ClaimRequestStructOutput]>;

    "build(bytes16,bytes16,uint256,uint8)"(
      groupId: PromiseOrValue<BytesLike>,
      groupTimestamp: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BigNumberish>,
      claimType: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[ClaimRequestStructOutput]>;

    "build(bytes16,bytes16,uint256,bool,bool)"(
      groupId: PromiseOrValue<BytesLike>,
      groupTimestamp: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BigNumberish>,
      isOptional: PromiseOrValue<boolean>,
      isSelectableByUser: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<[ClaimRequestStructOutput]>;

    "build(bytes16,uint256,uint8,bytes)"(
      groupId: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BigNumberish>,
      claimType: PromiseOrValue<BigNumberish>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[ClaimRequestStructOutput]>;

    "build(bytes16)"(
      groupId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[ClaimRequestStructOutput]>;

    "build(bytes16,bytes16,uint256,uint8,bool,bool,bytes)"(
      groupId: PromiseOrValue<BytesLike>,
      groupTimestamp: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BigNumberish>,
      claimType: PromiseOrValue<BigNumberish>,
      isOptional: PromiseOrValue<boolean>,
      isSelectableByUser: PromiseOrValue<boolean>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[ClaimRequestStructOutput]>;

    "build(bytes16,uint256,bytes)"(
      groupId: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BigNumberish>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[ClaimRequestStructOutput]>;

    "build(bytes16,bool,bool)"(
      groupId: PromiseOrValue<BytesLike>,
      isOptional: PromiseOrValue<boolean>,
      isSelectableByUser: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<[ClaimRequestStructOutput]>;

    "build(bytes16,bytes16,bytes)"(
      groupId: PromiseOrValue<BytesLike>,
      groupTimestamp: PromiseOrValue<BytesLike>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[ClaimRequestStructOutput]>;
  };

  DEFAULT_CLAIM_REQUEST_EXTRA_DATA(overrides?: CallOverrides): Promise<string>;

  DEFAULT_CLAIM_REQUEST_GROUP_TIMESTAMP(
    overrides?: CallOverrides
  ): Promise<string>;

  DEFAULT_CLAIM_REQUEST_IS_OPTIONAL(
    overrides?: CallOverrides
  ): Promise<boolean>;

  DEFAULT_CLAIM_REQUEST_IS_SELECTABLE_BY_USER(
    overrides?: CallOverrides
  ): Promise<boolean>;

  DEFAULT_CLAIM_REQUEST_TYPE(overrides?: CallOverrides): Promise<number>;

  DEFAULT_CLAIM_REQUEST_VALUE(overrides?: CallOverrides): Promise<BigNumber>;

  "build(bytes16,bytes16,uint8,bytes)"(
    groupId: PromiseOrValue<BytesLike>,
    groupTimestamp: PromiseOrValue<BytesLike>,
    claimType: PromiseOrValue<BigNumberish>,
    extraData: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<ClaimRequestStructOutput>;

  "build(bytes16,bytes16,uint256,bytes)"(
    groupId: PromiseOrValue<BytesLike>,
    groupTimestamp: PromiseOrValue<BytesLike>,
    value: PromiseOrValue<BigNumberish>,
    extraData: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<ClaimRequestStructOutput>;

  "build(bytes16,bytes16,bool,bool)"(
    groupId: PromiseOrValue<BytesLike>,
    groupTimestamp: PromiseOrValue<BytesLike>,
    isOptional: PromiseOrValue<boolean>,
    isSelectableByUser: PromiseOrValue<boolean>,
    overrides?: CallOverrides
  ): Promise<ClaimRequestStructOutput>;

  "build(bytes16,uint256,uint8,bool,bool)"(
    groupId: PromiseOrValue<BytesLike>,
    value: PromiseOrValue<BigNumberish>,
    claimType: PromiseOrValue<BigNumberish>,
    isOptional: PromiseOrValue<boolean>,
    isSelectableByUser: PromiseOrValue<boolean>,
    overrides?: CallOverrides
  ): Promise<ClaimRequestStructOutput>;

  "build(bytes16,uint256,bool,bool)"(
    groupId: PromiseOrValue<BytesLike>,
    value: PromiseOrValue<BigNumberish>,
    isOptional: PromiseOrValue<boolean>,
    isSelectableByUser: PromiseOrValue<boolean>,
    overrides?: CallOverrides
  ): Promise<ClaimRequestStructOutput>;

  "build(bytes16,bytes16,uint8,bool,bool)"(
    groupId: PromiseOrValue<BytesLike>,
    groupTimestamp: PromiseOrValue<BytesLike>,
    claimType: PromiseOrValue<BigNumberish>,
    isOptional: PromiseOrValue<boolean>,
    isSelectableByUser: PromiseOrValue<boolean>,
    overrides?: CallOverrides
  ): Promise<ClaimRequestStructOutput>;

  "build(bytes16,uint256,uint8)"(
    groupId: PromiseOrValue<BytesLike>,
    value: PromiseOrValue<BigNumberish>,
    claimType: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<ClaimRequestStructOutput>;

  "build(bytes16,bytes16,uint256)"(
    groupId: PromiseOrValue<BytesLike>,
    groupTimestamp: PromiseOrValue<BytesLike>,
    value: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<ClaimRequestStructOutput>;

  "build(bytes16,bytes16)"(
    groupId: PromiseOrValue<BytesLike>,
    groupTimestamp: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<ClaimRequestStructOutput>;

  "build(bytes16,bytes16,uint256,uint8,bool,bool)"(
    groupId: PromiseOrValue<BytesLike>,
    groupTimestamp: PromiseOrValue<BytesLike>,
    value: PromiseOrValue<BigNumberish>,
    claimType: PromiseOrValue<BigNumberish>,
    isOptional: PromiseOrValue<boolean>,
    isSelectableByUser: PromiseOrValue<boolean>,
    overrides?: CallOverrides
  ): Promise<ClaimRequestStructOutput>;

  "build(bytes16,bytes16,uint256,uint8,bytes)"(
    groupId: PromiseOrValue<BytesLike>,
    groupTimestamp: PromiseOrValue<BytesLike>,
    value: PromiseOrValue<BigNumberish>,
    claimType: PromiseOrValue<BigNumberish>,
    extraData: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<ClaimRequestStructOutput>;

  "build(bytes16,uint8)"(
    groupId: PromiseOrValue<BytesLike>,
    claimType: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<ClaimRequestStructOutput>;

  "build(bytes16,uint256)"(
    groupId: PromiseOrValue<BytesLike>,
    value: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<ClaimRequestStructOutput>;

  "build(bytes16,uint8,bytes)"(
    groupId: PromiseOrValue<BytesLike>,
    claimType: PromiseOrValue<BigNumberish>,
    extraData: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<ClaimRequestStructOutput>;

  "build(bytes16,bytes)"(
    groupId: PromiseOrValue<BytesLike>,
    extraData: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<ClaimRequestStructOutput>;

  "build(bytes16,uint8,bool,bool)"(
    groupId: PromiseOrValue<BytesLike>,
    claimType: PromiseOrValue<BigNumberish>,
    isOptional: PromiseOrValue<boolean>,
    isSelectableByUser: PromiseOrValue<boolean>,
    overrides?: CallOverrides
  ): Promise<ClaimRequestStructOutput>;

  "build(bytes16,bytes16,uint8)"(
    groupId: PromiseOrValue<BytesLike>,
    groupTimestamp: PromiseOrValue<BytesLike>,
    claimType: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<ClaimRequestStructOutput>;

  "build(bytes16,bytes16,uint256,uint8)"(
    groupId: PromiseOrValue<BytesLike>,
    groupTimestamp: PromiseOrValue<BytesLike>,
    value: PromiseOrValue<BigNumberish>,
    claimType: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<ClaimRequestStructOutput>;

  "build(bytes16,bytes16,uint256,bool,bool)"(
    groupId: PromiseOrValue<BytesLike>,
    groupTimestamp: PromiseOrValue<BytesLike>,
    value: PromiseOrValue<BigNumberish>,
    isOptional: PromiseOrValue<boolean>,
    isSelectableByUser: PromiseOrValue<boolean>,
    overrides?: CallOverrides
  ): Promise<ClaimRequestStructOutput>;

  "build(bytes16,uint256,uint8,bytes)"(
    groupId: PromiseOrValue<BytesLike>,
    value: PromiseOrValue<BigNumberish>,
    claimType: PromiseOrValue<BigNumberish>,
    extraData: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<ClaimRequestStructOutput>;

  "build(bytes16)"(
    groupId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<ClaimRequestStructOutput>;

  "build(bytes16,bytes16,uint256,uint8,bool,bool,bytes)"(
    groupId: PromiseOrValue<BytesLike>,
    groupTimestamp: PromiseOrValue<BytesLike>,
    value: PromiseOrValue<BigNumberish>,
    claimType: PromiseOrValue<BigNumberish>,
    isOptional: PromiseOrValue<boolean>,
    isSelectableByUser: PromiseOrValue<boolean>,
    extraData: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<ClaimRequestStructOutput>;

  "build(bytes16,uint256,bytes)"(
    groupId: PromiseOrValue<BytesLike>,
    value: PromiseOrValue<BigNumberish>,
    extraData: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<ClaimRequestStructOutput>;

  "build(bytes16,bool,bool)"(
    groupId: PromiseOrValue<BytesLike>,
    isOptional: PromiseOrValue<boolean>,
    isSelectableByUser: PromiseOrValue<boolean>,
    overrides?: CallOverrides
  ): Promise<ClaimRequestStructOutput>;

  "build(bytes16,bytes16,bytes)"(
    groupId: PromiseOrValue<BytesLike>,
    groupTimestamp: PromiseOrValue<BytesLike>,
    extraData: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<ClaimRequestStructOutput>;

  callStatic: {
    DEFAULT_CLAIM_REQUEST_EXTRA_DATA(
      overrides?: CallOverrides
    ): Promise<string>;

    DEFAULT_CLAIM_REQUEST_GROUP_TIMESTAMP(
      overrides?: CallOverrides
    ): Promise<string>;

    DEFAULT_CLAIM_REQUEST_IS_OPTIONAL(
      overrides?: CallOverrides
    ): Promise<boolean>;

    DEFAULT_CLAIM_REQUEST_IS_SELECTABLE_BY_USER(
      overrides?: CallOverrides
    ): Promise<boolean>;

    DEFAULT_CLAIM_REQUEST_TYPE(overrides?: CallOverrides): Promise<number>;

    DEFAULT_CLAIM_REQUEST_VALUE(overrides?: CallOverrides): Promise<BigNumber>;

    "build(bytes16,bytes16,uint8,bytes)"(
      groupId: PromiseOrValue<BytesLike>,
      groupTimestamp: PromiseOrValue<BytesLike>,
      claimType: PromiseOrValue<BigNumberish>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<ClaimRequestStructOutput>;

    "build(bytes16,bytes16,uint256,bytes)"(
      groupId: PromiseOrValue<BytesLike>,
      groupTimestamp: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BigNumberish>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<ClaimRequestStructOutput>;

    "build(bytes16,bytes16,bool,bool)"(
      groupId: PromiseOrValue<BytesLike>,
      groupTimestamp: PromiseOrValue<BytesLike>,
      isOptional: PromiseOrValue<boolean>,
      isSelectableByUser: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<ClaimRequestStructOutput>;

    "build(bytes16,uint256,uint8,bool,bool)"(
      groupId: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BigNumberish>,
      claimType: PromiseOrValue<BigNumberish>,
      isOptional: PromiseOrValue<boolean>,
      isSelectableByUser: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<ClaimRequestStructOutput>;

    "build(bytes16,uint256,bool,bool)"(
      groupId: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BigNumberish>,
      isOptional: PromiseOrValue<boolean>,
      isSelectableByUser: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<ClaimRequestStructOutput>;

    "build(bytes16,bytes16,uint8,bool,bool)"(
      groupId: PromiseOrValue<BytesLike>,
      groupTimestamp: PromiseOrValue<BytesLike>,
      claimType: PromiseOrValue<BigNumberish>,
      isOptional: PromiseOrValue<boolean>,
      isSelectableByUser: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<ClaimRequestStructOutput>;

    "build(bytes16,uint256,uint8)"(
      groupId: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BigNumberish>,
      claimType: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<ClaimRequestStructOutput>;

    "build(bytes16,bytes16,uint256)"(
      groupId: PromiseOrValue<BytesLike>,
      groupTimestamp: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<ClaimRequestStructOutput>;

    "build(bytes16,bytes16)"(
      groupId: PromiseOrValue<BytesLike>,
      groupTimestamp: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<ClaimRequestStructOutput>;

    "build(bytes16,bytes16,uint256,uint8,bool,bool)"(
      groupId: PromiseOrValue<BytesLike>,
      groupTimestamp: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BigNumberish>,
      claimType: PromiseOrValue<BigNumberish>,
      isOptional: PromiseOrValue<boolean>,
      isSelectableByUser: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<ClaimRequestStructOutput>;

    "build(bytes16,bytes16,uint256,uint8,bytes)"(
      groupId: PromiseOrValue<BytesLike>,
      groupTimestamp: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BigNumberish>,
      claimType: PromiseOrValue<BigNumberish>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<ClaimRequestStructOutput>;

    "build(bytes16,uint8)"(
      groupId: PromiseOrValue<BytesLike>,
      claimType: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<ClaimRequestStructOutput>;

    "build(bytes16,uint256)"(
      groupId: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<ClaimRequestStructOutput>;

    "build(bytes16,uint8,bytes)"(
      groupId: PromiseOrValue<BytesLike>,
      claimType: PromiseOrValue<BigNumberish>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<ClaimRequestStructOutput>;

    "build(bytes16,bytes)"(
      groupId: PromiseOrValue<BytesLike>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<ClaimRequestStructOutput>;

    "build(bytes16,uint8,bool,bool)"(
      groupId: PromiseOrValue<BytesLike>,
      claimType: PromiseOrValue<BigNumberish>,
      isOptional: PromiseOrValue<boolean>,
      isSelectableByUser: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<ClaimRequestStructOutput>;

    "build(bytes16,bytes16,uint8)"(
      groupId: PromiseOrValue<BytesLike>,
      groupTimestamp: PromiseOrValue<BytesLike>,
      claimType: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<ClaimRequestStructOutput>;

    "build(bytes16,bytes16,uint256,uint8)"(
      groupId: PromiseOrValue<BytesLike>,
      groupTimestamp: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BigNumberish>,
      claimType: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<ClaimRequestStructOutput>;

    "build(bytes16,bytes16,uint256,bool,bool)"(
      groupId: PromiseOrValue<BytesLike>,
      groupTimestamp: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BigNumberish>,
      isOptional: PromiseOrValue<boolean>,
      isSelectableByUser: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<ClaimRequestStructOutput>;

    "build(bytes16,uint256,uint8,bytes)"(
      groupId: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BigNumberish>,
      claimType: PromiseOrValue<BigNumberish>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<ClaimRequestStructOutput>;

    "build(bytes16)"(
      groupId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<ClaimRequestStructOutput>;

    "build(bytes16,bytes16,uint256,uint8,bool,bool,bytes)"(
      groupId: PromiseOrValue<BytesLike>,
      groupTimestamp: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BigNumberish>,
      claimType: PromiseOrValue<BigNumberish>,
      isOptional: PromiseOrValue<boolean>,
      isSelectableByUser: PromiseOrValue<boolean>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<ClaimRequestStructOutput>;

    "build(bytes16,uint256,bytes)"(
      groupId: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BigNumberish>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<ClaimRequestStructOutput>;

    "build(bytes16,bool,bool)"(
      groupId: PromiseOrValue<BytesLike>,
      isOptional: PromiseOrValue<boolean>,
      isSelectableByUser: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<ClaimRequestStructOutput>;

    "build(bytes16,bytes16,bytes)"(
      groupId: PromiseOrValue<BytesLike>,
      groupTimestamp: PromiseOrValue<BytesLike>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<ClaimRequestStructOutput>;
  };

  filters: {};

  estimateGas: {
    DEFAULT_CLAIM_REQUEST_EXTRA_DATA(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    DEFAULT_CLAIM_REQUEST_GROUP_TIMESTAMP(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    DEFAULT_CLAIM_REQUEST_IS_OPTIONAL(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    DEFAULT_CLAIM_REQUEST_IS_SELECTABLE_BY_USER(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    DEFAULT_CLAIM_REQUEST_TYPE(overrides?: CallOverrides): Promise<BigNumber>;

    DEFAULT_CLAIM_REQUEST_VALUE(overrides?: CallOverrides): Promise<BigNumber>;

    "build(bytes16,bytes16,uint8,bytes)"(
      groupId: PromiseOrValue<BytesLike>,
      groupTimestamp: PromiseOrValue<BytesLike>,
      claimType: PromiseOrValue<BigNumberish>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "build(bytes16,bytes16,uint256,bytes)"(
      groupId: PromiseOrValue<BytesLike>,
      groupTimestamp: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BigNumberish>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "build(bytes16,bytes16,bool,bool)"(
      groupId: PromiseOrValue<BytesLike>,
      groupTimestamp: PromiseOrValue<BytesLike>,
      isOptional: PromiseOrValue<boolean>,
      isSelectableByUser: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "build(bytes16,uint256,uint8,bool,bool)"(
      groupId: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BigNumberish>,
      claimType: PromiseOrValue<BigNumberish>,
      isOptional: PromiseOrValue<boolean>,
      isSelectableByUser: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "build(bytes16,uint256,bool,bool)"(
      groupId: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BigNumberish>,
      isOptional: PromiseOrValue<boolean>,
      isSelectableByUser: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "build(bytes16,bytes16,uint8,bool,bool)"(
      groupId: PromiseOrValue<BytesLike>,
      groupTimestamp: PromiseOrValue<BytesLike>,
      claimType: PromiseOrValue<BigNumberish>,
      isOptional: PromiseOrValue<boolean>,
      isSelectableByUser: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "build(bytes16,uint256,uint8)"(
      groupId: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BigNumberish>,
      claimType: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "build(bytes16,bytes16,uint256)"(
      groupId: PromiseOrValue<BytesLike>,
      groupTimestamp: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "build(bytes16,bytes16)"(
      groupId: PromiseOrValue<BytesLike>,
      groupTimestamp: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "build(bytes16,bytes16,uint256,uint8,bool,bool)"(
      groupId: PromiseOrValue<BytesLike>,
      groupTimestamp: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BigNumberish>,
      claimType: PromiseOrValue<BigNumberish>,
      isOptional: PromiseOrValue<boolean>,
      isSelectableByUser: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "build(bytes16,bytes16,uint256,uint8,bytes)"(
      groupId: PromiseOrValue<BytesLike>,
      groupTimestamp: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BigNumberish>,
      claimType: PromiseOrValue<BigNumberish>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "build(bytes16,uint8)"(
      groupId: PromiseOrValue<BytesLike>,
      claimType: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "build(bytes16,uint256)"(
      groupId: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "build(bytes16,uint8,bytes)"(
      groupId: PromiseOrValue<BytesLike>,
      claimType: PromiseOrValue<BigNumberish>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "build(bytes16,bytes)"(
      groupId: PromiseOrValue<BytesLike>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "build(bytes16,uint8,bool,bool)"(
      groupId: PromiseOrValue<BytesLike>,
      claimType: PromiseOrValue<BigNumberish>,
      isOptional: PromiseOrValue<boolean>,
      isSelectableByUser: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "build(bytes16,bytes16,uint8)"(
      groupId: PromiseOrValue<BytesLike>,
      groupTimestamp: PromiseOrValue<BytesLike>,
      claimType: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "build(bytes16,bytes16,uint256,uint8)"(
      groupId: PromiseOrValue<BytesLike>,
      groupTimestamp: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BigNumberish>,
      claimType: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "build(bytes16,bytes16,uint256,bool,bool)"(
      groupId: PromiseOrValue<BytesLike>,
      groupTimestamp: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BigNumberish>,
      isOptional: PromiseOrValue<boolean>,
      isSelectableByUser: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "build(bytes16,uint256,uint8,bytes)"(
      groupId: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BigNumberish>,
      claimType: PromiseOrValue<BigNumberish>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "build(bytes16)"(
      groupId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "build(bytes16,bytes16,uint256,uint8,bool,bool,bytes)"(
      groupId: PromiseOrValue<BytesLike>,
      groupTimestamp: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BigNumberish>,
      claimType: PromiseOrValue<BigNumberish>,
      isOptional: PromiseOrValue<boolean>,
      isSelectableByUser: PromiseOrValue<boolean>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "build(bytes16,uint256,bytes)"(
      groupId: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BigNumberish>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "build(bytes16,bool,bool)"(
      groupId: PromiseOrValue<BytesLike>,
      isOptional: PromiseOrValue<boolean>,
      isSelectableByUser: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "build(bytes16,bytes16,bytes)"(
      groupId: PromiseOrValue<BytesLike>,
      groupTimestamp: PromiseOrValue<BytesLike>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    DEFAULT_CLAIM_REQUEST_EXTRA_DATA(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    DEFAULT_CLAIM_REQUEST_GROUP_TIMESTAMP(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    DEFAULT_CLAIM_REQUEST_IS_OPTIONAL(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    DEFAULT_CLAIM_REQUEST_IS_SELECTABLE_BY_USER(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    DEFAULT_CLAIM_REQUEST_TYPE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    DEFAULT_CLAIM_REQUEST_VALUE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "build(bytes16,bytes16,uint8,bytes)"(
      groupId: PromiseOrValue<BytesLike>,
      groupTimestamp: PromiseOrValue<BytesLike>,
      claimType: PromiseOrValue<BigNumberish>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "build(bytes16,bytes16,uint256,bytes)"(
      groupId: PromiseOrValue<BytesLike>,
      groupTimestamp: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BigNumberish>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "build(bytes16,bytes16,bool,bool)"(
      groupId: PromiseOrValue<BytesLike>,
      groupTimestamp: PromiseOrValue<BytesLike>,
      isOptional: PromiseOrValue<boolean>,
      isSelectableByUser: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "build(bytes16,uint256,uint8,bool,bool)"(
      groupId: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BigNumberish>,
      claimType: PromiseOrValue<BigNumberish>,
      isOptional: PromiseOrValue<boolean>,
      isSelectableByUser: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "build(bytes16,uint256,bool,bool)"(
      groupId: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BigNumberish>,
      isOptional: PromiseOrValue<boolean>,
      isSelectableByUser: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "build(bytes16,bytes16,uint8,bool,bool)"(
      groupId: PromiseOrValue<BytesLike>,
      groupTimestamp: PromiseOrValue<BytesLike>,
      claimType: PromiseOrValue<BigNumberish>,
      isOptional: PromiseOrValue<boolean>,
      isSelectableByUser: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "build(bytes16,uint256,uint8)"(
      groupId: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BigNumberish>,
      claimType: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "build(bytes16,bytes16,uint256)"(
      groupId: PromiseOrValue<BytesLike>,
      groupTimestamp: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "build(bytes16,bytes16)"(
      groupId: PromiseOrValue<BytesLike>,
      groupTimestamp: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "build(bytes16,bytes16,uint256,uint8,bool,bool)"(
      groupId: PromiseOrValue<BytesLike>,
      groupTimestamp: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BigNumberish>,
      claimType: PromiseOrValue<BigNumberish>,
      isOptional: PromiseOrValue<boolean>,
      isSelectableByUser: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "build(bytes16,bytes16,uint256,uint8,bytes)"(
      groupId: PromiseOrValue<BytesLike>,
      groupTimestamp: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BigNumberish>,
      claimType: PromiseOrValue<BigNumberish>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "build(bytes16,uint8)"(
      groupId: PromiseOrValue<BytesLike>,
      claimType: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "build(bytes16,uint256)"(
      groupId: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "build(bytes16,uint8,bytes)"(
      groupId: PromiseOrValue<BytesLike>,
      claimType: PromiseOrValue<BigNumberish>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "build(bytes16,bytes)"(
      groupId: PromiseOrValue<BytesLike>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "build(bytes16,uint8,bool,bool)"(
      groupId: PromiseOrValue<BytesLike>,
      claimType: PromiseOrValue<BigNumberish>,
      isOptional: PromiseOrValue<boolean>,
      isSelectableByUser: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "build(bytes16,bytes16,uint8)"(
      groupId: PromiseOrValue<BytesLike>,
      groupTimestamp: PromiseOrValue<BytesLike>,
      claimType: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "build(bytes16,bytes16,uint256,uint8)"(
      groupId: PromiseOrValue<BytesLike>,
      groupTimestamp: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BigNumberish>,
      claimType: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "build(bytes16,bytes16,uint256,bool,bool)"(
      groupId: PromiseOrValue<BytesLike>,
      groupTimestamp: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BigNumberish>,
      isOptional: PromiseOrValue<boolean>,
      isSelectableByUser: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "build(bytes16,uint256,uint8,bytes)"(
      groupId: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BigNumberish>,
      claimType: PromiseOrValue<BigNumberish>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "build(bytes16)"(
      groupId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "build(bytes16,bytes16,uint256,uint8,bool,bool,bytes)"(
      groupId: PromiseOrValue<BytesLike>,
      groupTimestamp: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BigNumberish>,
      claimType: PromiseOrValue<BigNumberish>,
      isOptional: PromiseOrValue<boolean>,
      isSelectableByUser: PromiseOrValue<boolean>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "build(bytes16,uint256,bytes)"(
      groupId: PromiseOrValue<BytesLike>,
      value: PromiseOrValue<BigNumberish>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "build(bytes16,bool,bool)"(
      groupId: PromiseOrValue<BytesLike>,
      isOptional: PromiseOrValue<boolean>,
      isSelectableByUser: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "build(bytes16,bytes16,bytes)"(
      groupId: PromiseOrValue<BytesLike>,
      groupTimestamp: PromiseOrValue<BytesLike>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
