/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../../../common";

export type ClaimRequestStruct = {
  claimType: PromiseOrValue<BigNumberish>;
  groupId: PromiseOrValue<BytesLike>;
  groupTimestamp: PromiseOrValue<BytesLike>;
  value: PromiseOrValue<BigNumberish>;
  isOptional: PromiseOrValue<boolean>;
  isSelectableByUser: PromiseOrValue<boolean>;
  extraData: PromiseOrValue<BytesLike>;
};

export type ClaimRequestStructOutput = [
  number,
  string,
  string,
  BigNumber,
  boolean,
  boolean,
  string
] & {
  claimType: number;
  groupId: string;
  groupTimestamp: string;
  value: BigNumber;
  isOptional: boolean;
  isSelectableByUser: boolean;
  extraData: string;
};

export type AuthRequestStruct = {
  authType: PromiseOrValue<BigNumberish>;
  userId: PromiseOrValue<BigNumberish>;
  isAnon: PromiseOrValue<boolean>;
  isOptional: PromiseOrValue<boolean>;
  isSelectableByUser: PromiseOrValue<boolean>;
  extraData: PromiseOrValue<BytesLike>;
};

export type AuthRequestStructOutput = [
  number,
  BigNumber,
  boolean,
  boolean,
  boolean,
  string
] & {
  authType: number;
  userId: BigNumber;
  isAnon: boolean;
  isOptional: boolean;
  isSelectableByUser: boolean;
  extraData: string;
};

export type SignatureRequestStruct = {
  message: PromiseOrValue<BytesLike>;
  isSelectableByUser: PromiseOrValue<boolean>;
  extraData: PromiseOrValue<BytesLike>;
};

export type SignatureRequestStructOutput = [string, boolean, string] & {
  message: string;
  isSelectableByUser: boolean;
  extraData: string;
};

export type SismoConnectRequestStruct = {
  appId: PromiseOrValue<BytesLike>;
  namespace: PromiseOrValue<BytesLike>;
  auths: AuthRequestStruct[];
  claims: ClaimRequestStruct[];
  signature: SignatureRequestStruct;
};

export type SismoConnectRequestStructOutput = [
  string,
  string,
  AuthRequestStructOutput[],
  ClaimRequestStructOutput[],
  SignatureRequestStructOutput
] & {
  appId: string;
  namespace: string;
  auths: AuthRequestStructOutput[];
  claims: ClaimRequestStructOutput[];
  signature: SignatureRequestStructOutput;
};

export interface RequestBuilderInterface extends utils.Interface {
  functions: {
    "DEFAULT_NAMESPACE()": FunctionFragment;
    "build((uint8,bytes16,bytes16,uint256,bool,bool,bytes),bytes16)": FunctionFragment;
    "build((uint8,uint256,bool,bool,bool,bytes),(bytes,bool,bytes),bytes16)": FunctionFragment;
    "build((uint8,bytes16,bytes16,uint256,bool,bool,bytes)[],(bytes,bool,bytes),bytes16)": FunctionFragment;
    "build((uint8,uint256,bool,bool,bool,bytes)[],bytes16)": FunctionFragment;
    "build((uint8,uint256,bool,bool,bool,bytes)[],(uint8,bytes16,bytes16,uint256,bool,bool,bytes)[],bytes16,bytes16)": FunctionFragment;
    "build((uint8,uint256,bool,bool,bool,bytes),(bytes,bool,bytes),bytes16,bytes16)": FunctionFragment;
    "build((uint8,uint256,bool,bool,bool,bytes),(uint8,bytes16,bytes16,uint256,bool,bool,bytes),bytes16)": FunctionFragment;
    "build((uint8,bytes16,bytes16,uint256,bool,bool,bytes),(bytes,bool,bytes),bytes16)": FunctionFragment;
    "build((uint8,bytes16,bytes16,uint256,bool,bool,bytes)[],(bytes,bool,bytes),bytes16,bytes16)": FunctionFragment;
    "build((uint8,bytes16,bytes16,uint256,bool,bool,bytes),bytes16,bytes16)": FunctionFragment;
    "build((uint8,uint256,bool,bool,bool,bytes),bytes16)": FunctionFragment;
    "build((uint8,uint256,bool,bool,bool,bytes)[],(uint8,bytes16,bytes16,uint256,bool,bool,bytes)[],bytes16)": FunctionFragment;
    "build((uint8,uint256,bool,bool,bool,bytes)[],bytes16,bytes16)": FunctionFragment;
    "build((uint8,uint256,bool,bool,bool,bytes)[],(bytes,bool,bytes),bytes16,bytes16)": FunctionFragment;
    "build((uint8,bytes16,bytes16,uint256,bool,bool,bytes)[],bytes16,bytes16)": FunctionFragment;
    "build((uint8,bytes16,bytes16,uint256,bool,bool,bytes),(bytes,bool,bytes),bytes16,bytes16)": FunctionFragment;
    "build((uint8,uint256,bool,bool,bool,bytes),(uint8,bytes16,bytes16,uint256,bool,bool,bytes),bytes16,bytes16)": FunctionFragment;
    "build((uint8,uint256,bool,bool,bool,bytes),bytes16,bytes16)": FunctionFragment;
    "build((uint8,uint256,bool,bool,bool,bytes)[],(bytes,bool,bytes),bytes16)": FunctionFragment;
    "build((uint8,uint256,bool,bool,bool,bytes)[],(uint8,bytes16,bytes16,uint256,bool,bool,bytes)[],(bytes,bool,bytes),bytes16,bytes16)": FunctionFragment;
    "build((uint8,uint256,bool,bool,bool,bytes)[],(uint8,bytes16,bytes16,uint256,bool,bool,bytes)[],(bytes,bool,bytes),bytes16)": FunctionFragment;
    "build((uint8,uint256,bool,bool,bool,bytes),(uint8,bytes16,bytes16,uint256,bool,bool,bytes),(bytes,bool,bytes),bytes16)": FunctionFragment;
    "build((uint8,bytes16,bytes16,uint256,bool,bool,bytes)[],bytes16)": FunctionFragment;
    "build((uint8,uint256,bool,bool,bool,bytes),(uint8,bytes16,bytes16,uint256,bool,bool,bytes),(bytes,bool,bytes),bytes16,bytes16)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "DEFAULT_NAMESPACE"
      | "build((uint8,bytes16,bytes16,uint256,bool,bool,bytes),bytes16)"
      | "build((uint8,uint256,bool,bool,bool,bytes),(bytes,bool,bytes),bytes16)"
      | "build((uint8,bytes16,bytes16,uint256,bool,bool,bytes)[],(bytes,bool,bytes),bytes16)"
      | "build((uint8,uint256,bool,bool,bool,bytes)[],bytes16)"
      | "build((uint8,uint256,bool,bool,bool,bytes)[],(uint8,bytes16,bytes16,uint256,bool,bool,bytes)[],bytes16,bytes16)"
      | "build((uint8,uint256,bool,bool,bool,bytes),(bytes,bool,bytes),bytes16,bytes16)"
      | "build((uint8,uint256,bool,bool,bool,bytes),(uint8,bytes16,bytes16,uint256,bool,bool,bytes),bytes16)"
      | "build((uint8,bytes16,bytes16,uint256,bool,bool,bytes),(bytes,bool,bytes),bytes16)"
      | "build((uint8,bytes16,bytes16,uint256,bool,bool,bytes)[],(bytes,bool,bytes),bytes16,bytes16)"
      | "build((uint8,bytes16,bytes16,uint256,bool,bool,bytes),bytes16,bytes16)"
      | "build((uint8,uint256,bool,bool,bool,bytes),bytes16)"
      | "build((uint8,uint256,bool,bool,bool,bytes)[],(uint8,bytes16,bytes16,uint256,bool,bool,bytes)[],bytes16)"
      | "build((uint8,uint256,bool,bool,bool,bytes)[],bytes16,bytes16)"
      | "build((uint8,uint256,bool,bool,bool,bytes)[],(bytes,bool,bytes),bytes16,bytes16)"
      | "build((uint8,bytes16,bytes16,uint256,bool,bool,bytes)[],bytes16,bytes16)"
      | "build((uint8,bytes16,bytes16,uint256,bool,bool,bytes),(bytes,bool,bytes),bytes16,bytes16)"
      | "build((uint8,uint256,bool,bool,bool,bytes),(uint8,bytes16,bytes16,uint256,bool,bool,bytes),bytes16,bytes16)"
      | "build((uint8,uint256,bool,bool,bool,bytes),bytes16,bytes16)"
      | "build((uint8,uint256,bool,bool,bool,bytes)[],(bytes,bool,bytes),bytes16)"
      | "build((uint8,uint256,bool,bool,bool,bytes)[],(uint8,bytes16,bytes16,uint256,bool,bool,bytes)[],(bytes,bool,bytes),bytes16,bytes16)"
      | "build((uint8,uint256,bool,bool,bool,bytes)[],(uint8,bytes16,bytes16,uint256,bool,bool,bytes)[],(bytes,bool,bytes),bytes16)"
      | "build((uint8,uint256,bool,bool,bool,bytes),(uint8,bytes16,bytes16,uint256,bool,bool,bytes),(bytes,bool,bytes),bytes16)"
      | "build((uint8,bytes16,bytes16,uint256,bool,bool,bytes)[],bytes16)"
      | "build((uint8,uint256,bool,bool,bool,bytes),(uint8,bytes16,bytes16,uint256,bool,bool,bytes),(bytes,bool,bytes),bytes16,bytes16)"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_NAMESPACE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "build((uint8,bytes16,bytes16,uint256,bool,bool,bytes),bytes16)",
    values: [ClaimRequestStruct, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "build((uint8,uint256,bool,bool,bool,bytes),(bytes,bool,bytes),bytes16)",
    values: [
      AuthRequestStruct,
      SignatureRequestStruct,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "build((uint8,bytes16,bytes16,uint256,bool,bool,bytes)[],(bytes,bool,bytes),bytes16)",
    values: [
      ClaimRequestStruct[],
      SignatureRequestStruct,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "build((uint8,uint256,bool,bool,bool,bytes)[],bytes16)",
    values: [AuthRequestStruct[], PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "build((uint8,uint256,bool,bool,bool,bytes)[],(uint8,bytes16,bytes16,uint256,bool,bool,bytes)[],bytes16,bytes16)",
    values: [
      AuthRequestStruct[],
      ClaimRequestStruct[],
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "build((uint8,uint256,bool,bool,bool,bytes),(bytes,bool,bytes),bytes16,bytes16)",
    values: [
      AuthRequestStruct,
      SignatureRequestStruct,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "build((uint8,uint256,bool,bool,bool,bytes),(uint8,bytes16,bytes16,uint256,bool,bool,bytes),bytes16)",
    values: [AuthRequestStruct, ClaimRequestStruct, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "build((uint8,bytes16,bytes16,uint256,bool,bool,bytes),(bytes,bool,bytes),bytes16)",
    values: [
      ClaimRequestStruct,
      SignatureRequestStruct,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "build((uint8,bytes16,bytes16,uint256,bool,bool,bytes)[],(bytes,bool,bytes),bytes16,bytes16)",
    values: [
      ClaimRequestStruct[],
      SignatureRequestStruct,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "build((uint8,bytes16,bytes16,uint256,bool,bool,bytes),bytes16,bytes16)",
    values: [
      ClaimRequestStruct,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "build((uint8,uint256,bool,bool,bool,bytes),bytes16)",
    values: [AuthRequestStruct, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "build((uint8,uint256,bool,bool,bool,bytes)[],(uint8,bytes16,bytes16,uint256,bool,bool,bytes)[],bytes16)",
    values: [
      AuthRequestStruct[],
      ClaimRequestStruct[],
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "build((uint8,uint256,bool,bool,bool,bytes)[],bytes16,bytes16)",
    values: [
      AuthRequestStruct[],
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "build((uint8,uint256,bool,bool,bool,bytes)[],(bytes,bool,bytes),bytes16,bytes16)",
    values: [
      AuthRequestStruct[],
      SignatureRequestStruct,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "build((uint8,bytes16,bytes16,uint256,bool,bool,bytes)[],bytes16,bytes16)",
    values: [
      ClaimRequestStruct[],
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "build((uint8,bytes16,bytes16,uint256,bool,bool,bytes),(bytes,bool,bytes),bytes16,bytes16)",
    values: [
      ClaimRequestStruct,
      SignatureRequestStruct,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "build((uint8,uint256,bool,bool,bool,bytes),(uint8,bytes16,bytes16,uint256,bool,bool,bytes),bytes16,bytes16)",
    values: [
      AuthRequestStruct,
      ClaimRequestStruct,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "build((uint8,uint256,bool,bool,bool,bytes),bytes16,bytes16)",
    values: [
      AuthRequestStruct,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "build((uint8,uint256,bool,bool,bool,bytes)[],(bytes,bool,bytes),bytes16)",
    values: [
      AuthRequestStruct[],
      SignatureRequestStruct,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "build((uint8,uint256,bool,bool,bool,bytes)[],(uint8,bytes16,bytes16,uint256,bool,bool,bytes)[],(bytes,bool,bytes),bytes16,bytes16)",
    values: [
      AuthRequestStruct[],
      ClaimRequestStruct[],
      SignatureRequestStruct,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "build((uint8,uint256,bool,bool,bool,bytes)[],(uint8,bytes16,bytes16,uint256,bool,bool,bytes)[],(bytes,bool,bytes),bytes16)",
    values: [
      AuthRequestStruct[],
      ClaimRequestStruct[],
      SignatureRequestStruct,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "build((uint8,uint256,bool,bool,bool,bytes),(uint8,bytes16,bytes16,uint256,bool,bool,bytes),(bytes,bool,bytes),bytes16)",
    values: [
      AuthRequestStruct,
      ClaimRequestStruct,
      SignatureRequestStruct,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "build((uint8,bytes16,bytes16,uint256,bool,bool,bytes)[],bytes16)",
    values: [ClaimRequestStruct[], PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "build((uint8,uint256,bool,bool,bool,bytes),(uint8,bytes16,bytes16,uint256,bool,bool,bytes),(bytes,bool,bytes),bytes16,bytes16)",
    values: [
      AuthRequestStruct,
      ClaimRequestStruct,
      SignatureRequestStruct,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_NAMESPACE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "build((uint8,bytes16,bytes16,uint256,bool,bool,bytes),bytes16)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "build((uint8,uint256,bool,bool,bool,bytes),(bytes,bool,bytes),bytes16)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "build((uint8,bytes16,bytes16,uint256,bool,bool,bytes)[],(bytes,bool,bytes),bytes16)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "build((uint8,uint256,bool,bool,bool,bytes)[],bytes16)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "build((uint8,uint256,bool,bool,bool,bytes)[],(uint8,bytes16,bytes16,uint256,bool,bool,bytes)[],bytes16,bytes16)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "build((uint8,uint256,bool,bool,bool,bytes),(bytes,bool,bytes),bytes16,bytes16)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "build((uint8,uint256,bool,bool,bool,bytes),(uint8,bytes16,bytes16,uint256,bool,bool,bytes),bytes16)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "build((uint8,bytes16,bytes16,uint256,bool,bool,bytes),(bytes,bool,bytes),bytes16)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "build((uint8,bytes16,bytes16,uint256,bool,bool,bytes)[],(bytes,bool,bytes),bytes16,bytes16)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "build((uint8,bytes16,bytes16,uint256,bool,bool,bytes),bytes16,bytes16)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "build((uint8,uint256,bool,bool,bool,bytes),bytes16)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "build((uint8,uint256,bool,bool,bool,bytes)[],(uint8,bytes16,bytes16,uint256,bool,bool,bytes)[],bytes16)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "build((uint8,uint256,bool,bool,bool,bytes)[],bytes16,bytes16)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "build((uint8,uint256,bool,bool,bool,bytes)[],(bytes,bool,bytes),bytes16,bytes16)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "build((uint8,bytes16,bytes16,uint256,bool,bool,bytes)[],bytes16,bytes16)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "build((uint8,bytes16,bytes16,uint256,bool,bool,bytes),(bytes,bool,bytes),bytes16,bytes16)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "build((uint8,uint256,bool,bool,bool,bytes),(uint8,bytes16,bytes16,uint256,bool,bool,bytes),bytes16,bytes16)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "build((uint8,uint256,bool,bool,bool,bytes),bytes16,bytes16)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "build((uint8,uint256,bool,bool,bool,bytes)[],(bytes,bool,bytes),bytes16)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "build((uint8,uint256,bool,bool,bool,bytes)[],(uint8,bytes16,bytes16,uint256,bool,bool,bytes)[],(bytes,bool,bytes),bytes16,bytes16)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "build((uint8,uint256,bool,bool,bool,bytes)[],(uint8,bytes16,bytes16,uint256,bool,bool,bytes)[],(bytes,bool,bytes),bytes16)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "build((uint8,uint256,bool,bool,bool,bytes),(uint8,bytes16,bytes16,uint256,bool,bool,bytes),(bytes,bool,bytes),bytes16)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "build((uint8,bytes16,bytes16,uint256,bool,bool,bytes)[],bytes16)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "build((uint8,uint256,bool,bool,bool,bytes),(uint8,bytes16,bytes16,uint256,bool,bool,bytes),(bytes,bool,bytes),bytes16,bytes16)",
    data: BytesLike
  ): Result;

  events: {};
}

export interface RequestBuilder extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: RequestBuilderInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    DEFAULT_NAMESPACE(overrides?: CallOverrides): Promise<[string]>;

    "build((uint8,bytes16,bytes16,uint256,bool,bool,bytes),bytes16)"(
      claim: ClaimRequestStruct,
      appId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[SismoConnectRequestStructOutput]>;

    "build((uint8,uint256,bool,bool,bool,bytes),(bytes,bool,bytes),bytes16)"(
      auth: AuthRequestStruct,
      signature: SignatureRequestStruct,
      appId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[SismoConnectRequestStructOutput]>;

    "build((uint8,bytes16,bytes16,uint256,bool,bool,bytes)[],(bytes,bool,bytes),bytes16)"(
      claims: ClaimRequestStruct[],
      signature: SignatureRequestStruct,
      appId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[SismoConnectRequestStructOutput]>;

    "build((uint8,uint256,bool,bool,bool,bytes)[],bytes16)"(
      auths: AuthRequestStruct[],
      appId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[SismoConnectRequestStructOutput]>;

    "build((uint8,uint256,bool,bool,bool,bytes)[],(uint8,bytes16,bytes16,uint256,bool,bool,bytes)[],bytes16,bytes16)"(
      auths: AuthRequestStruct[],
      claims: ClaimRequestStruct[],
      appId: PromiseOrValue<BytesLike>,
      namespace: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[SismoConnectRequestStructOutput]>;

    "build((uint8,uint256,bool,bool,bool,bytes),(bytes,bool,bytes),bytes16,bytes16)"(
      auth: AuthRequestStruct,
      signature: SignatureRequestStruct,
      appId: PromiseOrValue<BytesLike>,
      namespace: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[SismoConnectRequestStructOutput]>;

    "build((uint8,uint256,bool,bool,bool,bytes),(uint8,bytes16,bytes16,uint256,bool,bool,bytes),bytes16)"(
      auth: AuthRequestStruct,
      claim: ClaimRequestStruct,
      appId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[SismoConnectRequestStructOutput]>;

    "build((uint8,bytes16,bytes16,uint256,bool,bool,bytes),(bytes,bool,bytes),bytes16)"(
      claim: ClaimRequestStruct,
      signature: SignatureRequestStruct,
      appId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[SismoConnectRequestStructOutput]>;

    "build((uint8,bytes16,bytes16,uint256,bool,bool,bytes)[],(bytes,bool,bytes),bytes16,bytes16)"(
      claims: ClaimRequestStruct[],
      signature: SignatureRequestStruct,
      appId: PromiseOrValue<BytesLike>,
      namespace: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[SismoConnectRequestStructOutput]>;

    "build((uint8,bytes16,bytes16,uint256,bool,bool,bytes),bytes16,bytes16)"(
      claim: ClaimRequestStruct,
      appId: PromiseOrValue<BytesLike>,
      namespace: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[SismoConnectRequestStructOutput]>;

    "build((uint8,uint256,bool,bool,bool,bytes),bytes16)"(
      auth: AuthRequestStruct,
      appId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[SismoConnectRequestStructOutput]>;

    "build((uint8,uint256,bool,bool,bool,bytes)[],(uint8,bytes16,bytes16,uint256,bool,bool,bytes)[],bytes16)"(
      auths: AuthRequestStruct[],
      claims: ClaimRequestStruct[],
      appId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[SismoConnectRequestStructOutput]>;

    "build((uint8,uint256,bool,bool,bool,bytes)[],bytes16,bytes16)"(
      auths: AuthRequestStruct[],
      appId: PromiseOrValue<BytesLike>,
      namespace: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[SismoConnectRequestStructOutput]>;

    "build((uint8,uint256,bool,bool,bool,bytes)[],(bytes,bool,bytes),bytes16,bytes16)"(
      auths: AuthRequestStruct[],
      signature: SignatureRequestStruct,
      appId: PromiseOrValue<BytesLike>,
      namespace: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[SismoConnectRequestStructOutput]>;

    "build((uint8,bytes16,bytes16,uint256,bool,bool,bytes)[],bytes16,bytes16)"(
      claims: ClaimRequestStruct[],
      appId: PromiseOrValue<BytesLike>,
      namespace: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[SismoConnectRequestStructOutput]>;

    "build((uint8,bytes16,bytes16,uint256,bool,bool,bytes),(bytes,bool,bytes),bytes16,bytes16)"(
      claim: ClaimRequestStruct,
      signature: SignatureRequestStruct,
      appId: PromiseOrValue<BytesLike>,
      namespace: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[SismoConnectRequestStructOutput]>;

    "build((uint8,uint256,bool,bool,bool,bytes),(uint8,bytes16,bytes16,uint256,bool,bool,bytes),bytes16,bytes16)"(
      auth: AuthRequestStruct,
      claim: ClaimRequestStruct,
      appId: PromiseOrValue<BytesLike>,
      namespace: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[SismoConnectRequestStructOutput]>;

    "build((uint8,uint256,bool,bool,bool,bytes),bytes16,bytes16)"(
      auth: AuthRequestStruct,
      appId: PromiseOrValue<BytesLike>,
      namespace: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[SismoConnectRequestStructOutput]>;

    "build((uint8,uint256,bool,bool,bool,bytes)[],(bytes,bool,bytes),bytes16)"(
      auths: AuthRequestStruct[],
      signature: SignatureRequestStruct,
      appId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[SismoConnectRequestStructOutput]>;

    "build((uint8,uint256,bool,bool,bool,bytes)[],(uint8,bytes16,bytes16,uint256,bool,bool,bytes)[],(bytes,bool,bytes),bytes16,bytes16)"(
      auths: AuthRequestStruct[],
      claims: ClaimRequestStruct[],
      signature: SignatureRequestStruct,
      appId: PromiseOrValue<BytesLike>,
      namespace: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[SismoConnectRequestStructOutput]>;

    "build((uint8,uint256,bool,bool,bool,bytes)[],(uint8,bytes16,bytes16,uint256,bool,bool,bytes)[],(bytes,bool,bytes),bytes16)"(
      auths: AuthRequestStruct[],
      claims: ClaimRequestStruct[],
      signature: SignatureRequestStruct,
      appId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[SismoConnectRequestStructOutput]>;

    "build((uint8,uint256,bool,bool,bool,bytes),(uint8,bytes16,bytes16,uint256,bool,bool,bytes),(bytes,bool,bytes),bytes16)"(
      auth: AuthRequestStruct,
      claim: ClaimRequestStruct,
      signature: SignatureRequestStruct,
      appId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[SismoConnectRequestStructOutput]>;

    "build((uint8,bytes16,bytes16,uint256,bool,bool,bytes)[],bytes16)"(
      claims: ClaimRequestStruct[],
      appId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[SismoConnectRequestStructOutput]>;

    "build((uint8,uint256,bool,bool,bool,bytes),(uint8,bytes16,bytes16,uint256,bool,bool,bytes),(bytes,bool,bytes),bytes16,bytes16)"(
      auth: AuthRequestStruct,
      claim: ClaimRequestStruct,
      signature: SignatureRequestStruct,
      appId: PromiseOrValue<BytesLike>,
      namespace: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[SismoConnectRequestStructOutput]>;
  };

  DEFAULT_NAMESPACE(overrides?: CallOverrides): Promise<string>;

  "build((uint8,bytes16,bytes16,uint256,bool,bool,bytes),bytes16)"(
    claim: ClaimRequestStruct,
    appId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<SismoConnectRequestStructOutput>;

  "build((uint8,uint256,bool,bool,bool,bytes),(bytes,bool,bytes),bytes16)"(
    auth: AuthRequestStruct,
    signature: SignatureRequestStruct,
    appId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<SismoConnectRequestStructOutput>;

  "build((uint8,bytes16,bytes16,uint256,bool,bool,bytes)[],(bytes,bool,bytes),bytes16)"(
    claims: ClaimRequestStruct[],
    signature: SignatureRequestStruct,
    appId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<SismoConnectRequestStructOutput>;

  "build((uint8,uint256,bool,bool,bool,bytes)[],bytes16)"(
    auths: AuthRequestStruct[],
    appId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<SismoConnectRequestStructOutput>;

  "build((uint8,uint256,bool,bool,bool,bytes)[],(uint8,bytes16,bytes16,uint256,bool,bool,bytes)[],bytes16,bytes16)"(
    auths: AuthRequestStruct[],
    claims: ClaimRequestStruct[],
    appId: PromiseOrValue<BytesLike>,
    namespace: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<SismoConnectRequestStructOutput>;

  "build((uint8,uint256,bool,bool,bool,bytes),(bytes,bool,bytes),bytes16,bytes16)"(
    auth: AuthRequestStruct,
    signature: SignatureRequestStruct,
    appId: PromiseOrValue<BytesLike>,
    namespace: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<SismoConnectRequestStructOutput>;

  "build((uint8,uint256,bool,bool,bool,bytes),(uint8,bytes16,bytes16,uint256,bool,bool,bytes),bytes16)"(
    auth: AuthRequestStruct,
    claim: ClaimRequestStruct,
    appId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<SismoConnectRequestStructOutput>;

  "build((uint8,bytes16,bytes16,uint256,bool,bool,bytes),(bytes,bool,bytes),bytes16)"(
    claim: ClaimRequestStruct,
    signature: SignatureRequestStruct,
    appId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<SismoConnectRequestStructOutput>;

  "build((uint8,bytes16,bytes16,uint256,bool,bool,bytes)[],(bytes,bool,bytes),bytes16,bytes16)"(
    claims: ClaimRequestStruct[],
    signature: SignatureRequestStruct,
    appId: PromiseOrValue<BytesLike>,
    namespace: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<SismoConnectRequestStructOutput>;

  "build((uint8,bytes16,bytes16,uint256,bool,bool,bytes),bytes16,bytes16)"(
    claim: ClaimRequestStruct,
    appId: PromiseOrValue<BytesLike>,
    namespace: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<SismoConnectRequestStructOutput>;

  "build((uint8,uint256,bool,bool,bool,bytes),bytes16)"(
    auth: AuthRequestStruct,
    appId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<SismoConnectRequestStructOutput>;

  "build((uint8,uint256,bool,bool,bool,bytes)[],(uint8,bytes16,bytes16,uint256,bool,bool,bytes)[],bytes16)"(
    auths: AuthRequestStruct[],
    claims: ClaimRequestStruct[],
    appId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<SismoConnectRequestStructOutput>;

  "build((uint8,uint256,bool,bool,bool,bytes)[],bytes16,bytes16)"(
    auths: AuthRequestStruct[],
    appId: PromiseOrValue<BytesLike>,
    namespace: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<SismoConnectRequestStructOutput>;

  "build((uint8,uint256,bool,bool,bool,bytes)[],(bytes,bool,bytes),bytes16,bytes16)"(
    auths: AuthRequestStruct[],
    signature: SignatureRequestStruct,
    appId: PromiseOrValue<BytesLike>,
    namespace: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<SismoConnectRequestStructOutput>;

  "build((uint8,bytes16,bytes16,uint256,bool,bool,bytes)[],bytes16,bytes16)"(
    claims: ClaimRequestStruct[],
    appId: PromiseOrValue<BytesLike>,
    namespace: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<SismoConnectRequestStructOutput>;

  "build((uint8,bytes16,bytes16,uint256,bool,bool,bytes),(bytes,bool,bytes),bytes16,bytes16)"(
    claim: ClaimRequestStruct,
    signature: SignatureRequestStruct,
    appId: PromiseOrValue<BytesLike>,
    namespace: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<SismoConnectRequestStructOutput>;

  "build((uint8,uint256,bool,bool,bool,bytes),(uint8,bytes16,bytes16,uint256,bool,bool,bytes),bytes16,bytes16)"(
    auth: AuthRequestStruct,
    claim: ClaimRequestStruct,
    appId: PromiseOrValue<BytesLike>,
    namespace: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<SismoConnectRequestStructOutput>;

  "build((uint8,uint256,bool,bool,bool,bytes),bytes16,bytes16)"(
    auth: AuthRequestStruct,
    appId: PromiseOrValue<BytesLike>,
    namespace: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<SismoConnectRequestStructOutput>;

  "build((uint8,uint256,bool,bool,bool,bytes)[],(bytes,bool,bytes),bytes16)"(
    auths: AuthRequestStruct[],
    signature: SignatureRequestStruct,
    appId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<SismoConnectRequestStructOutput>;

  "build((uint8,uint256,bool,bool,bool,bytes)[],(uint8,bytes16,bytes16,uint256,bool,bool,bytes)[],(bytes,bool,bytes),bytes16,bytes16)"(
    auths: AuthRequestStruct[],
    claims: ClaimRequestStruct[],
    signature: SignatureRequestStruct,
    appId: PromiseOrValue<BytesLike>,
    namespace: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<SismoConnectRequestStructOutput>;

  "build((uint8,uint256,bool,bool,bool,bytes)[],(uint8,bytes16,bytes16,uint256,bool,bool,bytes)[],(bytes,bool,bytes),bytes16)"(
    auths: AuthRequestStruct[],
    claims: ClaimRequestStruct[],
    signature: SignatureRequestStruct,
    appId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<SismoConnectRequestStructOutput>;

  "build((uint8,uint256,bool,bool,bool,bytes),(uint8,bytes16,bytes16,uint256,bool,bool,bytes),(bytes,bool,bytes),bytes16)"(
    auth: AuthRequestStruct,
    claim: ClaimRequestStruct,
    signature: SignatureRequestStruct,
    appId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<SismoConnectRequestStructOutput>;

  "build((uint8,bytes16,bytes16,uint256,bool,bool,bytes)[],bytes16)"(
    claims: ClaimRequestStruct[],
    appId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<SismoConnectRequestStructOutput>;

  "build((uint8,uint256,bool,bool,bool,bytes),(uint8,bytes16,bytes16,uint256,bool,bool,bytes),(bytes,bool,bytes),bytes16,bytes16)"(
    auth: AuthRequestStruct,
    claim: ClaimRequestStruct,
    signature: SignatureRequestStruct,
    appId: PromiseOrValue<BytesLike>,
    namespace: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<SismoConnectRequestStructOutput>;

  callStatic: {
    DEFAULT_NAMESPACE(overrides?: CallOverrides): Promise<string>;

    "build((uint8,bytes16,bytes16,uint256,bool,bool,bytes),bytes16)"(
      claim: ClaimRequestStruct,
      appId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<SismoConnectRequestStructOutput>;

    "build((uint8,uint256,bool,bool,bool,bytes),(bytes,bool,bytes),bytes16)"(
      auth: AuthRequestStruct,
      signature: SignatureRequestStruct,
      appId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<SismoConnectRequestStructOutput>;

    "build((uint8,bytes16,bytes16,uint256,bool,bool,bytes)[],(bytes,bool,bytes),bytes16)"(
      claims: ClaimRequestStruct[],
      signature: SignatureRequestStruct,
      appId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<SismoConnectRequestStructOutput>;

    "build((uint8,uint256,bool,bool,bool,bytes)[],bytes16)"(
      auths: AuthRequestStruct[],
      appId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<SismoConnectRequestStructOutput>;

    "build((uint8,uint256,bool,bool,bool,bytes)[],(uint8,bytes16,bytes16,uint256,bool,bool,bytes)[],bytes16,bytes16)"(
      auths: AuthRequestStruct[],
      claims: ClaimRequestStruct[],
      appId: PromiseOrValue<BytesLike>,
      namespace: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<SismoConnectRequestStructOutput>;

    "build((uint8,uint256,bool,bool,bool,bytes),(bytes,bool,bytes),bytes16,bytes16)"(
      auth: AuthRequestStruct,
      signature: SignatureRequestStruct,
      appId: PromiseOrValue<BytesLike>,
      namespace: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<SismoConnectRequestStructOutput>;

    "build((uint8,uint256,bool,bool,bool,bytes),(uint8,bytes16,bytes16,uint256,bool,bool,bytes),bytes16)"(
      auth: AuthRequestStruct,
      claim: ClaimRequestStruct,
      appId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<SismoConnectRequestStructOutput>;

    "build((uint8,bytes16,bytes16,uint256,bool,bool,bytes),(bytes,bool,bytes),bytes16)"(
      claim: ClaimRequestStruct,
      signature: SignatureRequestStruct,
      appId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<SismoConnectRequestStructOutput>;

    "build((uint8,bytes16,bytes16,uint256,bool,bool,bytes)[],(bytes,bool,bytes),bytes16,bytes16)"(
      claims: ClaimRequestStruct[],
      signature: SignatureRequestStruct,
      appId: PromiseOrValue<BytesLike>,
      namespace: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<SismoConnectRequestStructOutput>;

    "build((uint8,bytes16,bytes16,uint256,bool,bool,bytes),bytes16,bytes16)"(
      claim: ClaimRequestStruct,
      appId: PromiseOrValue<BytesLike>,
      namespace: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<SismoConnectRequestStructOutput>;

    "build((uint8,uint256,bool,bool,bool,bytes),bytes16)"(
      auth: AuthRequestStruct,
      appId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<SismoConnectRequestStructOutput>;

    "build((uint8,uint256,bool,bool,bool,bytes)[],(uint8,bytes16,bytes16,uint256,bool,bool,bytes)[],bytes16)"(
      auths: AuthRequestStruct[],
      claims: ClaimRequestStruct[],
      appId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<SismoConnectRequestStructOutput>;

    "build((uint8,uint256,bool,bool,bool,bytes)[],bytes16,bytes16)"(
      auths: AuthRequestStruct[],
      appId: PromiseOrValue<BytesLike>,
      namespace: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<SismoConnectRequestStructOutput>;

    "build((uint8,uint256,bool,bool,bool,bytes)[],(bytes,bool,bytes),bytes16,bytes16)"(
      auths: AuthRequestStruct[],
      signature: SignatureRequestStruct,
      appId: PromiseOrValue<BytesLike>,
      namespace: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<SismoConnectRequestStructOutput>;

    "build((uint8,bytes16,bytes16,uint256,bool,bool,bytes)[],bytes16,bytes16)"(
      claims: ClaimRequestStruct[],
      appId: PromiseOrValue<BytesLike>,
      namespace: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<SismoConnectRequestStructOutput>;

    "build((uint8,bytes16,bytes16,uint256,bool,bool,bytes),(bytes,bool,bytes),bytes16,bytes16)"(
      claim: ClaimRequestStruct,
      signature: SignatureRequestStruct,
      appId: PromiseOrValue<BytesLike>,
      namespace: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<SismoConnectRequestStructOutput>;

    "build((uint8,uint256,bool,bool,bool,bytes),(uint8,bytes16,bytes16,uint256,bool,bool,bytes),bytes16,bytes16)"(
      auth: AuthRequestStruct,
      claim: ClaimRequestStruct,
      appId: PromiseOrValue<BytesLike>,
      namespace: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<SismoConnectRequestStructOutput>;

    "build((uint8,uint256,bool,bool,bool,bytes),bytes16,bytes16)"(
      auth: AuthRequestStruct,
      appId: PromiseOrValue<BytesLike>,
      namespace: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<SismoConnectRequestStructOutput>;

    "build((uint8,uint256,bool,bool,bool,bytes)[],(bytes,bool,bytes),bytes16)"(
      auths: AuthRequestStruct[],
      signature: SignatureRequestStruct,
      appId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<SismoConnectRequestStructOutput>;

    "build((uint8,uint256,bool,bool,bool,bytes)[],(uint8,bytes16,bytes16,uint256,bool,bool,bytes)[],(bytes,bool,bytes),bytes16,bytes16)"(
      auths: AuthRequestStruct[],
      claims: ClaimRequestStruct[],
      signature: SignatureRequestStruct,
      appId: PromiseOrValue<BytesLike>,
      namespace: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<SismoConnectRequestStructOutput>;

    "build((uint8,uint256,bool,bool,bool,bytes)[],(uint8,bytes16,bytes16,uint256,bool,bool,bytes)[],(bytes,bool,bytes),bytes16)"(
      auths: AuthRequestStruct[],
      claims: ClaimRequestStruct[],
      signature: SignatureRequestStruct,
      appId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<SismoConnectRequestStructOutput>;

    "build((uint8,uint256,bool,bool,bool,bytes),(uint8,bytes16,bytes16,uint256,bool,bool,bytes),(bytes,bool,bytes),bytes16)"(
      auth: AuthRequestStruct,
      claim: ClaimRequestStruct,
      signature: SignatureRequestStruct,
      appId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<SismoConnectRequestStructOutput>;

    "build((uint8,bytes16,bytes16,uint256,bool,bool,bytes)[],bytes16)"(
      claims: ClaimRequestStruct[],
      appId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<SismoConnectRequestStructOutput>;

    "build((uint8,uint256,bool,bool,bool,bytes),(uint8,bytes16,bytes16,uint256,bool,bool,bytes),(bytes,bool,bytes),bytes16,bytes16)"(
      auth: AuthRequestStruct,
      claim: ClaimRequestStruct,
      signature: SignatureRequestStruct,
      appId: PromiseOrValue<BytesLike>,
      namespace: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<SismoConnectRequestStructOutput>;
  };

  filters: {};

  estimateGas: {
    DEFAULT_NAMESPACE(overrides?: CallOverrides): Promise<BigNumber>;

    "build((uint8,bytes16,bytes16,uint256,bool,bool,bytes),bytes16)"(
      claim: ClaimRequestStruct,
      appId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "build((uint8,uint256,bool,bool,bool,bytes),(bytes,bool,bytes),bytes16)"(
      auth: AuthRequestStruct,
      signature: SignatureRequestStruct,
      appId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "build((uint8,bytes16,bytes16,uint256,bool,bool,bytes)[],(bytes,bool,bytes),bytes16)"(
      claims: ClaimRequestStruct[],
      signature: SignatureRequestStruct,
      appId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "build((uint8,uint256,bool,bool,bool,bytes)[],bytes16)"(
      auths: AuthRequestStruct[],
      appId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "build((uint8,uint256,bool,bool,bool,bytes)[],(uint8,bytes16,bytes16,uint256,bool,bool,bytes)[],bytes16,bytes16)"(
      auths: AuthRequestStruct[],
      claims: ClaimRequestStruct[],
      appId: PromiseOrValue<BytesLike>,
      namespace: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "build((uint8,uint256,bool,bool,bool,bytes),(bytes,bool,bytes),bytes16,bytes16)"(
      auth: AuthRequestStruct,
      signature: SignatureRequestStruct,
      appId: PromiseOrValue<BytesLike>,
      namespace: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "build((uint8,uint256,bool,bool,bool,bytes),(uint8,bytes16,bytes16,uint256,bool,bool,bytes),bytes16)"(
      auth: AuthRequestStruct,
      claim: ClaimRequestStruct,
      appId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "build((uint8,bytes16,bytes16,uint256,bool,bool,bytes),(bytes,bool,bytes),bytes16)"(
      claim: ClaimRequestStruct,
      signature: SignatureRequestStruct,
      appId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "build((uint8,bytes16,bytes16,uint256,bool,bool,bytes)[],(bytes,bool,bytes),bytes16,bytes16)"(
      claims: ClaimRequestStruct[],
      signature: SignatureRequestStruct,
      appId: PromiseOrValue<BytesLike>,
      namespace: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "build((uint8,bytes16,bytes16,uint256,bool,bool,bytes),bytes16,bytes16)"(
      claim: ClaimRequestStruct,
      appId: PromiseOrValue<BytesLike>,
      namespace: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "build((uint8,uint256,bool,bool,bool,bytes),bytes16)"(
      auth: AuthRequestStruct,
      appId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "build((uint8,uint256,bool,bool,bool,bytes)[],(uint8,bytes16,bytes16,uint256,bool,bool,bytes)[],bytes16)"(
      auths: AuthRequestStruct[],
      claims: ClaimRequestStruct[],
      appId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "build((uint8,uint256,bool,bool,bool,bytes)[],bytes16,bytes16)"(
      auths: AuthRequestStruct[],
      appId: PromiseOrValue<BytesLike>,
      namespace: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "build((uint8,uint256,bool,bool,bool,bytes)[],(bytes,bool,bytes),bytes16,bytes16)"(
      auths: AuthRequestStruct[],
      signature: SignatureRequestStruct,
      appId: PromiseOrValue<BytesLike>,
      namespace: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "build((uint8,bytes16,bytes16,uint256,bool,bool,bytes)[],bytes16,bytes16)"(
      claims: ClaimRequestStruct[],
      appId: PromiseOrValue<BytesLike>,
      namespace: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "build((uint8,bytes16,bytes16,uint256,bool,bool,bytes),(bytes,bool,bytes),bytes16,bytes16)"(
      claim: ClaimRequestStruct,
      signature: SignatureRequestStruct,
      appId: PromiseOrValue<BytesLike>,
      namespace: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "build((uint8,uint256,bool,bool,bool,bytes),(uint8,bytes16,bytes16,uint256,bool,bool,bytes),bytes16,bytes16)"(
      auth: AuthRequestStruct,
      claim: ClaimRequestStruct,
      appId: PromiseOrValue<BytesLike>,
      namespace: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "build((uint8,uint256,bool,bool,bool,bytes),bytes16,bytes16)"(
      auth: AuthRequestStruct,
      appId: PromiseOrValue<BytesLike>,
      namespace: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "build((uint8,uint256,bool,bool,bool,bytes)[],(bytes,bool,bytes),bytes16)"(
      auths: AuthRequestStruct[],
      signature: SignatureRequestStruct,
      appId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "build((uint8,uint256,bool,bool,bool,bytes)[],(uint8,bytes16,bytes16,uint256,bool,bool,bytes)[],(bytes,bool,bytes),bytes16,bytes16)"(
      auths: AuthRequestStruct[],
      claims: ClaimRequestStruct[],
      signature: SignatureRequestStruct,
      appId: PromiseOrValue<BytesLike>,
      namespace: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "build((uint8,uint256,bool,bool,bool,bytes)[],(uint8,bytes16,bytes16,uint256,bool,bool,bytes)[],(bytes,bool,bytes),bytes16)"(
      auths: AuthRequestStruct[],
      claims: ClaimRequestStruct[],
      signature: SignatureRequestStruct,
      appId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "build((uint8,uint256,bool,bool,bool,bytes),(uint8,bytes16,bytes16,uint256,bool,bool,bytes),(bytes,bool,bytes),bytes16)"(
      auth: AuthRequestStruct,
      claim: ClaimRequestStruct,
      signature: SignatureRequestStruct,
      appId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "build((uint8,bytes16,bytes16,uint256,bool,bool,bytes)[],bytes16)"(
      claims: ClaimRequestStruct[],
      appId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "build((uint8,uint256,bool,bool,bool,bytes),(uint8,bytes16,bytes16,uint256,bool,bool,bytes),(bytes,bool,bytes),bytes16,bytes16)"(
      auth: AuthRequestStruct,
      claim: ClaimRequestStruct,
      signature: SignatureRequestStruct,
      appId: PromiseOrValue<BytesLike>,
      namespace: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    DEFAULT_NAMESPACE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "build((uint8,bytes16,bytes16,uint256,bool,bool,bytes),bytes16)"(
      claim: ClaimRequestStruct,
      appId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "build((uint8,uint256,bool,bool,bool,bytes),(bytes,bool,bytes),bytes16)"(
      auth: AuthRequestStruct,
      signature: SignatureRequestStruct,
      appId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "build((uint8,bytes16,bytes16,uint256,bool,bool,bytes)[],(bytes,bool,bytes),bytes16)"(
      claims: ClaimRequestStruct[],
      signature: SignatureRequestStruct,
      appId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "build((uint8,uint256,bool,bool,bool,bytes)[],bytes16)"(
      auths: AuthRequestStruct[],
      appId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "build((uint8,uint256,bool,bool,bool,bytes)[],(uint8,bytes16,bytes16,uint256,bool,bool,bytes)[],bytes16,bytes16)"(
      auths: AuthRequestStruct[],
      claims: ClaimRequestStruct[],
      appId: PromiseOrValue<BytesLike>,
      namespace: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "build((uint8,uint256,bool,bool,bool,bytes),(bytes,bool,bytes),bytes16,bytes16)"(
      auth: AuthRequestStruct,
      signature: SignatureRequestStruct,
      appId: PromiseOrValue<BytesLike>,
      namespace: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "build((uint8,uint256,bool,bool,bool,bytes),(uint8,bytes16,bytes16,uint256,bool,bool,bytes),bytes16)"(
      auth: AuthRequestStruct,
      claim: ClaimRequestStruct,
      appId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "build((uint8,bytes16,bytes16,uint256,bool,bool,bytes),(bytes,bool,bytes),bytes16)"(
      claim: ClaimRequestStruct,
      signature: SignatureRequestStruct,
      appId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "build((uint8,bytes16,bytes16,uint256,bool,bool,bytes)[],(bytes,bool,bytes),bytes16,bytes16)"(
      claims: ClaimRequestStruct[],
      signature: SignatureRequestStruct,
      appId: PromiseOrValue<BytesLike>,
      namespace: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "build((uint8,bytes16,bytes16,uint256,bool,bool,bytes),bytes16,bytes16)"(
      claim: ClaimRequestStruct,
      appId: PromiseOrValue<BytesLike>,
      namespace: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "build((uint8,uint256,bool,bool,bool,bytes),bytes16)"(
      auth: AuthRequestStruct,
      appId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "build((uint8,uint256,bool,bool,bool,bytes)[],(uint8,bytes16,bytes16,uint256,bool,bool,bytes)[],bytes16)"(
      auths: AuthRequestStruct[],
      claims: ClaimRequestStruct[],
      appId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "build((uint8,uint256,bool,bool,bool,bytes)[],bytes16,bytes16)"(
      auths: AuthRequestStruct[],
      appId: PromiseOrValue<BytesLike>,
      namespace: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "build((uint8,uint256,bool,bool,bool,bytes)[],(bytes,bool,bytes),bytes16,bytes16)"(
      auths: AuthRequestStruct[],
      signature: SignatureRequestStruct,
      appId: PromiseOrValue<BytesLike>,
      namespace: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "build((uint8,bytes16,bytes16,uint256,bool,bool,bytes)[],bytes16,bytes16)"(
      claims: ClaimRequestStruct[],
      appId: PromiseOrValue<BytesLike>,
      namespace: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "build((uint8,bytes16,bytes16,uint256,bool,bool,bytes),(bytes,bool,bytes),bytes16,bytes16)"(
      claim: ClaimRequestStruct,
      signature: SignatureRequestStruct,
      appId: PromiseOrValue<BytesLike>,
      namespace: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "build((uint8,uint256,bool,bool,bool,bytes),(uint8,bytes16,bytes16,uint256,bool,bool,bytes),bytes16,bytes16)"(
      auth: AuthRequestStruct,
      claim: ClaimRequestStruct,
      appId: PromiseOrValue<BytesLike>,
      namespace: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "build((uint8,uint256,bool,bool,bool,bytes),bytes16,bytes16)"(
      auth: AuthRequestStruct,
      appId: PromiseOrValue<BytesLike>,
      namespace: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "build((uint8,uint256,bool,bool,bool,bytes)[],(bytes,bool,bytes),bytes16)"(
      auths: AuthRequestStruct[],
      signature: SignatureRequestStruct,
      appId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "build((uint8,uint256,bool,bool,bool,bytes)[],(uint8,bytes16,bytes16,uint256,bool,bool,bytes)[],(bytes,bool,bytes),bytes16,bytes16)"(
      auths: AuthRequestStruct[],
      claims: ClaimRequestStruct[],
      signature: SignatureRequestStruct,
      appId: PromiseOrValue<BytesLike>,
      namespace: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "build((uint8,uint256,bool,bool,bool,bytes)[],(uint8,bytes16,bytes16,uint256,bool,bool,bytes)[],(bytes,bool,bytes),bytes16)"(
      auths: AuthRequestStruct[],
      claims: ClaimRequestStruct[],
      signature: SignatureRequestStruct,
      appId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "build((uint8,uint256,bool,bool,bool,bytes),(uint8,bytes16,bytes16,uint256,bool,bool,bytes),(bytes,bool,bytes),bytes16)"(
      auth: AuthRequestStruct,
      claim: ClaimRequestStruct,
      signature: SignatureRequestStruct,
      appId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "build((uint8,bytes16,bytes16,uint256,bool,bool,bytes)[],bytes16)"(
      claims: ClaimRequestStruct[],
      appId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "build((uint8,uint256,bool,bool,bool,bytes),(uint8,bytes16,bytes16,uint256,bool,bool,bytes),(bytes,bool,bytes),bytes16,bytes16)"(
      auth: AuthRequestStruct,
      claim: ClaimRequestStruct,
      signature: SignatureRequestStruct,
      appId: PromiseOrValue<BytesLike>,
      namespace: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
